/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../components/confirmdialog/confirmdialog';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '../../../components/button/button';
import * as import4 from '@angular/common/src/localization';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/i18n/tokens';
import * as import7 from '@angular/core/src/render/api';
import * as import8 from '@angular/core/src/linker/view';
import * as import9 from '@angular/core/src/linker/element';
import * as import10 from '../../../components/dom/domhandler';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/core/src/linker/view_utils';
import * as import13 from '@angular/core/src/linker/view_type';
import * as import14 from '@angular/core/src/change_detection/change_detection';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '../../../components/common/api';
import * as import17 from '@angular/core/src/metadata/view';
import * as import18 from '@angular/core/src/linker/component_factory';
import * as import19 from '@angular/core/src/animation/animation_style_util';
import * as import20 from '@angular/core/src/animation/animation_sequence_player';
import * as import21 from '@angular/core/src/animation/animation_styles';
import * as import22 from '@angular/core/src/animation/animation_keyframe';
import * as import23 from '@angular/core/src/animation/animation_player';
import * as import24 from '@angular/common/src/directives/ng_class';
import * as import25 from '@angular/common/src/directives/ng_if';
import * as import26 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import27 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/core/src/security';
class ConfirmDialogModuleInjector extends import0.NgModuleInjector<import1.ConfirmDialogModule> {
  _CommonModule_0:import2.CommonModule;
  _ButtonModule_1:import3.ButtonModule;
  _ConfirmDialogModule_2:import1.ConfirmDialogModule;
  __LOCALE_ID_3:any;
  __NgLocalization_4:import4.NgLocaleLocalization;
  __TRANSLATIONS_FORMAT_5:any;
  constructor(parent:import5.Injector) {
    super(parent,[],[]);
  }
  get _LOCALE_ID_3():any {
    if ((this.__LOCALE_ID_3 == (null as any))) { (this.__LOCALE_ID_3 = (null as any)); }
    return this.__LOCALE_ID_3;
  }
  get _NgLocalization_4():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == (null as any))) { (this.__NgLocalization_4 = new import4.NgLocaleLocalization(this._LOCALE_ID_3)); }
    return this.__NgLocalization_4;
  }
  get _TRANSLATIONS_FORMAT_5():any {
    if ((this.__TRANSLATIONS_FORMAT_5 == (null as any))) { (this.__TRANSLATIONS_FORMAT_5 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_5;
  }
  createInternal():import1.ConfirmDialogModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ButtonModule_1 = new import3.ButtonModule();
    this._ConfirmDialogModule_2 = new import1.ConfirmDialogModule();
    return this._ConfirmDialogModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ButtonModule)) { return this._ButtonModule_1; }
    if ((token === import1.ConfirmDialogModule)) { return this._ConfirmDialogModule_2; }
    if ((token === import6.LOCALE_ID)) { return this._LOCALE_ID_3; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import6.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ConfirmDialogModuleNgFactory:import0.NgModuleFactory<import1.ConfirmDialogModule> = new import0.NgModuleFactory(ConfirmDialogModuleInjector,import1.ConfirmDialogModule);
var renderType_ConfirmDialog_Host:import7.RenderComponentType = (null as any);
class _View_ConfirmDialog_Host0 extends import8.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import9.AppElement;
  _DomHandler_0_4:import10.DomHandler;
  _ConfirmDialog_0_5:import1.ConfirmDialog;
  _query_Footer_0_0:import11.QueryList<any>;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_ConfirmDialog_Host0,renderType_ConfirmDialog_Host,import13.ViewType.HOST,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.selectOrCreateHostElement('p-confirmDialog',rootSelector,(null as any));
    this._appEl_0 = new import9.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ConfirmDialog0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DomHandler_0_4 = new import10.DomHandler();
    this._ConfirmDialog_0_5 = new import1.ConfirmDialog(new import15.ElementRef(this._el_0),this._DomHandler_0_4,this.renderer,this.parentInjector.get(import16.ConfirmationService));
    this._query_Footer_0_0 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._ConfirmDialog_0_5,[],compView_0);
    this._query_Footer_0_0.reset([]);
    this._ConfirmDialog_0_5.footer = this._query_Footer_0_0.first;
    compView_0.create(this._ConfirmDialog_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.DomHandler) && (0 === requestNodeIndex))) { return this._DomHandler_0_4; }
    if (((token === import1.ConfirmDialog) && (0 === requestNodeIndex))) { return this._ConfirmDialog_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._ConfirmDialog_0_5.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._ConfirmDialog_0_5.ngOnDestroy();
  }
}
function viewFactory_ConfirmDialog_Host0(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  if ((renderType_ConfirmDialog_Host === (null as any))) { (renderType_ConfirmDialog_Host = viewUtils.createRenderComponentType('',0,import17.ViewEncapsulation.None,[],{})); }
  return new _View_ConfirmDialog_Host0(viewUtils,parentInjector,declarationEl);
}
export const ConfirmDialogNgFactory:import18.ComponentFactory<import1.ConfirmDialog> = new import18.ComponentFactory<import1.ConfirmDialog>('p-confirmDialog',viewFactory_ConfirmDialog_Host0,import1.ConfirmDialog);
const styles_ConfirmDialog:any[] = [];
var ConfirmDialog_dialogState_states:any = {
  hidden: {opacity: 0},
  visible: {opacity: 1},
  '*': {}
}
;
function ConfirmDialog_dialogState_factory(view:import8.AppView<any>,element:any,currentState:any,nextState:any):void {
  view.cancelActiveAnimation(element,'dialogState',(nextState == 'void'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = ConfirmDialog_dialogState_states['*'];
  var startStateStyles:any = ConfirmDialog_dialogState_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = ConfirmDialog_dialogState_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  import19.renderStyles(element,view.renderer,import19.clearStyles(startStateStyles));
  if (((player == (null as any)) && ((currentState == 'visible') && (nextState == 'hidden')))) {
      player = new import20.AnimationSequencePlayer([view.renderer.animate(element,new import21.AnimationStyles(import19.collectAndResolveStyles(collectedStyles,[startStateStyles])),import19.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import22.AnimationKeyframe(0,new import21.AnimationStyles(import19.collectAndResolveStyles(collectedStyles,[{}]))),
        new import22.AnimationKeyframe(1,new import21.AnimationStyles(import19.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),400,0,'ease-in')]);
    totalTime = 400;
  }
  if (((player == (null as any)) && ((currentState == 'hidden') && (nextState == 'visible')))) {
      player = new import20.AnimationSequencePlayer([view.renderer.animate(element,new import21.AnimationStyles(import19.collectAndResolveStyles(collectedStyles,[startStateStyles])),import19.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import22.AnimationKeyframe(0,new import21.AnimationStyles(import19.collectAndResolveStyles(collectedStyles,[{}]))),
        new import22.AnimationKeyframe(1,new import21.AnimationStyles(import19.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),400,0,'ease-out')]);
    totalTime = 400;
  }
  if ((player == (null as any))) { (player = new import23.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    import19.renderStyles(element,view.renderer,import19.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  view.queueAnimation(element,'dialogState',player,totalTime,currentState,nextState);
}
var renderType_ConfirmDialog:import7.RenderComponentType = (null as any);
class _View_ConfirmDialog0 extends import8.AppView<import1.ConfirmDialog> {
  _text_0:any;
  _el_1:any;
  _NgClass_1_3:import24.NgClass;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _appEl_5:import9.AppElement;
  _TemplateRef_5_5:any;
  _NgIf_5_6:import25.NgIf;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import9.AppElement;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import25.NgIf;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import9.AppElement;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import25.NgIf;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _appEl_20:import9.AppElement;
  _TemplateRef_20_5:any;
  _NgIf_20_6:import25.NgIf;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _map_0:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_ConfirmDialog0,renderType_ConfirmDialog,import13.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._NgClass_1_3 = new import24.NgClass(this.parentInjector.get(import26.IterableDiffers),this.parentInjector.get(import27.KeyValueDiffers),new import15.ElementRef(this._el_1),this.renderer);
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-corner-top');
    this._text_4 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_5 = new import9.AppElement(5,3,this,this._anchor_5);
    this._TemplateRef_5_5 = new import28.TemplateRef_(this._appEl_5,viewFactory_ConfirmDialog1);
    this._NgIf_5_6 = new import25.NgIf(this._appEl_5.vcRef,this._TemplateRef_5_5);
    this._text_6 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_7 = new import9.AppElement(7,3,this,this._anchor_7);
    this._TemplateRef_7_5 = new import28.TemplateRef_(this._appEl_7,viewFactory_ConfirmDialog2);
    this._NgIf_7_6 = new import25.NgIf(this._appEl_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_9 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','ui-dialog-content ui-widget-content');
    this._text_11 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'i',(null as any));
    this._text_13 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_10,'span',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','ui-confirmdialog-message');
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._text_17 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._appEl_18 = new import9.AppElement(18,1,this,this._anchor_18);
    this._TemplateRef_18_5 = new import28.TemplateRef_(this._appEl_18,viewFactory_ConfirmDialog3);
    this._NgIf_18_6 = new import25.NgIf(this._appEl_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._appEl_20 = new import9.AppElement(20,1,this,this._anchor_20);
    this._TemplateRef_20_5 = new import28.TemplateRef_(this._appEl_20,viewFactory_ConfirmDialog4);
    this._NgIf_20_6 = new import25.NgIf(this._appEl_20.vcRef,this._TemplateRef_20_5);
    this._text_21 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._expr_1 = import14.UNINITIALIZED;
    this._expr_2 = import14.UNINITIALIZED;
    this._expr_3 = import14.UNINITIALIZED;
    this._expr_4 = import14.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_1,'mousedown',this.eventHandler(this._handle_mousedown_1_0.bind(this)));
    this._map_0 = import12.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'ui-dialog ui-confirmdialog ui-widget ui-widget-content ui-corner-all ui-shadow': p0,
        'ui-dialog-rtl': p1
      }
      ;
    });
    this._expr_5 = import14.UNINITIALIZED;
    this._expr_6 = import14.UNINITIALIZED;
    this._expr_7 = import14.UNINITIALIZED;
    this._expr_8 = import14.UNINITIALIZED;
    this._expr_9 = import14.UNINITIALIZED;
    this._expr_10 = import14.UNINITIALIZED;
    this._expr_11 = import14.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._text_22
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import25.NgIf) && (5 === requestNodeIndex))) { return this._NgIf_5_6; }
    if (((token === import28.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import25.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6; }
    if (((token === import28.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import25.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6; }
    if (((token === import28.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import25.NgIf) && (20 === requestNodeIndex))) { return this._NgIf_20_6; }
    if (((token === import24.NgClass) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._NgClass_1_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = (this.context.visible? 'visible': 'hidden');
    if (import12.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      var oldRenderVar:any = this._expr_4;
      if ((oldRenderVar == import14.UNINITIALIZED)) { (oldRenderVar = 'void'); }
      var newRenderVar:any = currVal_4;
      if ((newRenderVar == import14.UNINITIALIZED)) { (newRenderVar = 'void'); }
      this.componentType.animations['dialogState'](this,this._el_1,oldRenderVar,newRenderVar);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._map_0(true,this.context.rtl);
    if (import12.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgClass_1_3.ngClass = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (!throwOnChange) { this._NgClass_1_3.ngDoCheck(); }
    const currVal_6:any = this.context.header;
    if (import12.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_5_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.context.closable;
    if (import12.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgIf_7_6.ngIf = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = this.context.footer;
    if (import12.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgIf_18_6.ngIf = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:boolean = !this.context.footer;
    if (import12.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgIf_20_6.ngIf = currVal_11;
      this._expr_11 = currVal_11;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = (this.context.visible? 'block': 'none');
    if (import12.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_1,'display',((this.viewUtils.sanitizer.sanitize(import29.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import29.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.width;
    if (import12.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementStyle(this._el_1,'width',((this.viewUtils.sanitizer.sanitize(import29.SecurityContext.STYLE,currVal_2) == (null as any))? (null as any): (this.viewUtils.sanitizer.sanitize(import29.SecurityContext.STYLE,currVal_2).toString() + 'px')));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.height;
    if (import12.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementStyle(this._el_1,'height',((this.viewUtils.sanitizer.sanitize(import29.SecurityContext.STYLE,currVal_3) == (null as any))? (null as any): (this.viewUtils.sanitizer.sanitize(import29.SecurityContext.STYLE,currVal_3).toString() + 'px')));
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this.context.icon;
    if (import12.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_12,'className',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import12.interpolate(1,'',this.context.message,'');
    if (import12.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_15,currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  detachInternal():void {
    this.componentType.animations['dialogState'](this,this._el_1,this._expr_4,'void');
  }
  private _handle_mousedown_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.moveOnTop()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ConfirmDialog0(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<import1.ConfirmDialog> {
  if ((renderType_ConfirmDialog === (null as any))) { (renderType_ConfirmDialog = viewUtils.createRenderComponentType('c:/Users/eirwn/Documents/primeng-min/components/confirmdialog/confirmdialog.ts class ConfirmDialog - inline template',1,import17.ViewEncapsulation.None,styles_ConfirmDialog,{dialogState: ConfirmDialog_dialogState_factory})); }
  return new _View_ConfirmDialog0(viewUtils,parentInjector,declarationEl);
}
class _View_ConfirmDialog1 extends import8.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_ConfirmDialog1,renderType_ConfirmDialog,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-dialog-title');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import12.interpolate(1,'',this.parent.context.header,'');
    if (import12.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ConfirmDialog1(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_ConfirmDialog1(viewUtils,parentInjector,declarationEl);
}
class _View_ConfirmDialog2 extends import8.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import24.NgClass;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _map_0:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_ConfirmDialog2,renderType_ConfirmDialog,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this.renderer.setElementAttribute(this._el_0,'href','#');
    this.renderer.setElementAttribute(this._el_0,'role','button');
    this._NgClass_0_3 = new import24.NgClass(this.parent.parentInjector.get(import26.IterableDiffers),this.parent.parentInjector.get(import27.KeyValueDiffers),new import15.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'span',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','fa fa-fw fa-close');
    this._text_3 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'mouseenter',this.eventHandler(this._handle_mouseenter_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'mouseleave',this.eventHandler(this._handle_mouseleave_0_2.bind(this)));
    this._map_0 = import12.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'ui-dialog-titlebar-icon ui-dialog-titlebar-close ui-corner-all': p0,
        'ui-state-hover': p1
      }
      ;
    });
    this._expr_3 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgClass_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = this._map_0(true,this.parent.context.hoverCloseIcon);
    if (import12.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgClass_0_3.ngClass = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (!throwOnChange) { this._NgClass_0_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.hide($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.hoverCloseIcon = true)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.hoverCloseIcon = false)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ConfirmDialog2(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_ConfirmDialog2(viewUtils,parentInjector,declarationEl);
}
class _View_ConfirmDialog3 extends import8.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_ConfirmDialog3,renderType_ConfirmDialog,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-dialog-buttonpane ui-widget-content ui-helper-clearfix');
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this.renderer.projectNodes(this._el_0,import12.flattenNestedViewRenderNodes(this.projectableNodes[0]));
    this._text_2 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ConfirmDialog3(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_ConfirmDialog3(viewUtils,parentInjector,declarationEl);
}
class _View_ConfirmDialog4 extends import8.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import9.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import25.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import9.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import25.NgIf;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_ConfirmDialog4,renderType_ConfirmDialog,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-dialog-buttonpane ui-widget-content ui-helper-clearfix');
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import9.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import28.TemplateRef_(this._appEl_2,viewFactory_ConfirmDialog5);
    this._NgIf_2_6 = new import25.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import9.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import28.TemplateRef_(this._appEl_4,viewFactory_ConfirmDialog6);
    this._NgIf_4_6 = new import25.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._expr_0 = import14.UNINITIALIZED;
    this._expr_1 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import25.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import28.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import25.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.rejectVisible;
    if (import12.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.acceptVisible;
    if (import12.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ConfirmDialog4(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_ConfirmDialog4(viewUtils,parentInjector,declarationEl);
}
class _View_ConfirmDialog5 extends import8.AppView<any> {
  _el_0:any;
  _DomHandler_0_3:import10.DomHandler;
  _Button_0_4:import3.Button;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_ConfirmDialog5,renderType_ConfirmDialog,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'pButton','');
    this.renderer.setElementAttribute(this._el_0,'type','button');
    this._DomHandler_0_3 = new import10.DomHandler();
    this._Button_0_4 = new import3.Button(new import15.ElementRef(this._el_0),this._DomHandler_0_3);
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'mouseenter',this.eventHandler(this._handle_mouseenter_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'mouseleave',this.eventHandler(this._handle_mouseleave_0_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_0,'mousedown',this.eventHandler(this._handle_mousedown_0_3.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_0,'mouseup',this.eventHandler(this._handle_mouseup_0_4.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_0,'focus',this.eventHandler(this._handle_focus_0_5.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_0,'blur',this.eventHandler(this._handle_blur_0_6.bind(this)));
    this._expr_7 = import14.UNINITIALIZED;
    this._expr_8 = import14.UNINITIALIZED;
    this._expr_9 = import14.UNINITIALIZED;
    this._expr_10 = import14.UNINITIALIZED;
    this._expr_11 = import14.UNINITIALIZED;
    this._expr_12 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.DomHandler) && (0 === requestNodeIndex))) { return this._DomHandler_0_3; }
    if (((token === import3.Button) && (0 === requestNodeIndex))) { return this._Button_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7:any = this.parent.parent.context.rejectIcon;
    if (import12.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Button_0_4.icon = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.parent.parent.context.rejectLabel;
    if (import12.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Button_0_4.label = currVal_8;
      this._expr_8 = currVal_8;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_9:any = (this._Button_0_4.hover && !this._Button_0_4.isDisabled());
    if (import12.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_0,'ui-state-hover',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Button_0_4.focus;
    if (import12.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_0,'ui-state-focus',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._Button_0_4.active;
    if (import12.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_0,'ui-state-active',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._Button_0_4.isDisabled();
    if (import12.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_0,'ui-state-disabled',currVal_12);
      this._expr_12 = currVal_12;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Button_0_4.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.reject()) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_0_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onMouseDown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_0_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onMouseUp($event)) !== false);
    return (true && pd_0);
  }
  private _handle_focus_0_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onFocus($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_0_6($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onBlur($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ConfirmDialog5(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_ConfirmDialog5(viewUtils,parentInjector,declarationEl);
}
class _View_ConfirmDialog6 extends import8.AppView<any> {
  _el_0:any;
  _DomHandler_0_3:import10.DomHandler;
  _Button_0_4:import3.Button;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_ConfirmDialog6,renderType_ConfirmDialog,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'pButton','');
    this.renderer.setElementAttribute(this._el_0,'type','button');
    this._DomHandler_0_3 = new import10.DomHandler();
    this._Button_0_4 = new import3.Button(new import15.ElementRef(this._el_0),this._DomHandler_0_3);
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'mouseenter',this.eventHandler(this._handle_mouseenter_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'mouseleave',this.eventHandler(this._handle_mouseleave_0_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_0,'mousedown',this.eventHandler(this._handle_mousedown_0_3.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_0,'mouseup',this.eventHandler(this._handle_mouseup_0_4.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_0,'focus',this.eventHandler(this._handle_focus_0_5.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_0,'blur',this.eventHandler(this._handle_blur_0_6.bind(this)));
    this._expr_7 = import14.UNINITIALIZED;
    this._expr_8 = import14.UNINITIALIZED;
    this._expr_9 = import14.UNINITIALIZED;
    this._expr_10 = import14.UNINITIALIZED;
    this._expr_11 = import14.UNINITIALIZED;
    this._expr_12 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.DomHandler) && (0 === requestNodeIndex))) { return this._DomHandler_0_3; }
    if (((token === import3.Button) && (0 === requestNodeIndex))) { return this._Button_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7:any = this.parent.parent.context.acceptIcon;
    if (import12.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Button_0_4.icon = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.parent.parent.context.acceptLabel;
    if (import12.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Button_0_4.label = currVal_8;
      this._expr_8 = currVal_8;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_9:any = (this._Button_0_4.hover && !this._Button_0_4.isDisabled());
    if (import12.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_0,'ui-state-hover',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Button_0_4.focus;
    if (import12.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_0,'ui-state-focus',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._Button_0_4.active;
    if (import12.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_0,'ui-state-active',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._Button_0_4.isDisabled();
    if (import12.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_0,'ui-state-disabled',currVal_12);
      this._expr_12 = currVal_12;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Button_0_4.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.accept()) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_0_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onMouseDown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_0_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onMouseUp($event)) !== false);
    return (true && pd_0);
  }
  private _handle_focus_0_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onFocus($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_0_6($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_0_4.onBlur($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ConfirmDialog6(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_ConfirmDialog6(viewUtils,parentInjector,declarationEl);
}