/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../components/orderlist/orderlist';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '../../../components/button/button';
import * as import4 from '../../../components/common/shared';
import * as import5 from '@angular/common/src/localization';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/i18n/tokens';
import * as import8 from '@angular/core/src/render/api';
import * as import9 from '@angular/core/src/linker/view';
import * as import10 from '@angular/core/src/linker/element';
import * as import11 from '../../../components/dom/domhandler';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '@angular/core/src/linker/view_utils';
import * as import14 from '@angular/core/src/linker/view_type';
import * as import15 from '@angular/core/src/change_detection/change_detection';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/core/src/metadata/view';
import * as import18 from '@angular/core/src/linker/component_factory';
import * as import19 from '@angular/common/src/directives/ng_class';
import * as import20 from '@angular/common/src/directives/ng_style';
import * as import21 from '@angular/common/src/directives/ng_if';
import * as import22 from '@angular/common/src/directives/ng_for';
import * as import23 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import24 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import25 from '@angular/core/src/linker/template_ref';
class OrderListModuleInjector extends import0.NgModuleInjector<import1.OrderListModule> {
  _CommonModule_0:import2.CommonModule;
  _ButtonModule_1:import3.ButtonModule;
  _SharedModule_2:import4.SharedModule;
  _OrderListModule_3:import1.OrderListModule;
  __LOCALE_ID_4:any;
  __NgLocalization_5:import5.NgLocaleLocalization;
  __TRANSLATIONS_FORMAT_6:any;
  constructor(parent:import6.Injector) {
    super(parent,[],[]);
  }
  get _LOCALE_ID_4():any {
    if ((this.__LOCALE_ID_4 == (null as any))) { (this.__LOCALE_ID_4 = (null as any)); }
    return this.__LOCALE_ID_4;
  }
  get _NgLocalization_5():import5.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == (null as any))) { (this.__NgLocalization_5 = new import5.NgLocaleLocalization(this._LOCALE_ID_4)); }
    return this.__NgLocalization_5;
  }
  get _TRANSLATIONS_FORMAT_6():any {
    if ((this.__TRANSLATIONS_FORMAT_6 == (null as any))) { (this.__TRANSLATIONS_FORMAT_6 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_6;
  }
  createInternal():import1.OrderListModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ButtonModule_1 = new import3.ButtonModule();
    this._SharedModule_2 = new import4.SharedModule();
    this._OrderListModule_3 = new import1.OrderListModule();
    return this._OrderListModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ButtonModule)) { return this._ButtonModule_1; }
    if ((token === import4.SharedModule)) { return this._SharedModule_2; }
    if ((token === import1.OrderListModule)) { return this._OrderListModule_3; }
    if ((token === import7.LOCALE_ID)) { return this._LOCALE_ID_4; }
    if ((token === import5.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import7.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_6; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const OrderListModuleNgFactory:import0.NgModuleFactory<import1.OrderListModule> = new import0.NgModuleFactory(OrderListModuleInjector,import1.OrderListModule);
var renderType_OrderList_Host:import8.RenderComponentType = (null as any);
class _View_OrderList_Host0 extends import9.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import10.AppElement;
  _DomHandler_0_4:import11.DomHandler;
  _OrderList_0_5:import1.OrderList;
  _query_TemplateRef_0_0:import12.QueryList<any>;
  constructor(viewUtils:import13.ViewUtils,parentInjector:import6.Injector,declarationEl:import10.AppElement) {
    super(_View_OrderList_Host0,renderType_OrderList_Host,import14.ViewType.HOST,viewUtils,parentInjector,declarationEl,import15.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import10.AppElement {
    this._el_0 = this.selectOrCreateHostElement('p-orderList',rootSelector,(null as any));
    this._appEl_0 = new import10.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_OrderList0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DomHandler_0_4 = new import11.DomHandler();
    this._OrderList_0_5 = new import1.OrderList(new import16.ElementRef(this._el_0),this._DomHandler_0_4);
    this._query_TemplateRef_0_0 = new import12.QueryList<any>();
    this._appEl_0.initComponent(this._OrderList_0_5,[],compView_0);
    this._query_TemplateRef_0_0.reset([]);
    this._OrderList_0_5.itemTemplate = this._query_TemplateRef_0_0.first;
    compView_0.create(this._OrderList_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.DomHandler) && (0 === requestNodeIndex))) { return this._DomHandler_0_4; }
    if (((token === import1.OrderList) && (0 === requestNodeIndex))) { return this._OrderList_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._OrderList_0_5.ngAfterViewInit(); }
      this._OrderList_0_5.ngAfterViewChecked();
    }
  }
}
function viewFactory_OrderList_Host0(viewUtils:import13.ViewUtils,parentInjector:import6.Injector,declarationEl:import10.AppElement):import9.AppView<any> {
  if ((renderType_OrderList_Host === (null as any))) { (renderType_OrderList_Host = viewUtils.createRenderComponentType('',0,import17.ViewEncapsulation.None,[],{})); }
  return new _View_OrderList_Host0(viewUtils,parentInjector,declarationEl);
}
export const OrderListNgFactory:import18.ComponentFactory<import1.OrderList> = new import18.ComponentFactory<import1.OrderList>('p-orderList',viewFactory_OrderList_Host0,import1.OrderList);
const styles_OrderList:any[] = [];
var renderType_OrderList:import8.RenderComponentType = (null as any);
class _View_OrderList0 extends import9.AppView<import1.OrderList> {
  _text_0:any;
  _el_1:any;
  _NgClass_1_3:import19.NgClass;
  _NgStyle_1_4:import20.NgStyle;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _DomHandler_7_3:import11.DomHandler;
  _Button_7_4:import3.Button;
  _text_8:any;
  _el_9:any;
  _DomHandler_9_3:import11.DomHandler;
  _Button_9_4:import3.Button;
  _text_10:any;
  _el_11:any;
  _DomHandler_11_3:import11.DomHandler;
  _Button_11_4:import3.Button;
  _text_12:any;
  _el_13:any;
  _DomHandler_13_3:import11.DomHandler;
  _Button_13_4:import3.Button;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import10.AppElement;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import21.NgIf;
  _text_19:any;
  _el_20:any;
  _NgStyle_20_3:import20.NgStyle;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import10.AppElement;
  _TemplateRef_22_5:any;
  _NgFor_22_6:import22.NgFor;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  /*private*/ _expr_0:any;
  _map_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  constructor(viewUtils:import13.ViewUtils,parentInjector:import6.Injector,declarationEl:import10.AppElement) {
    super(_View_OrderList0,renderType_OrderList,import14.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import15.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import10.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._NgClass_1_3 = new import19.NgClass(this.parentInjector.get(import23.IterableDiffers),this.parentInjector.get(import24.KeyValueDiffers),new import16.ElementRef(this._el_1),this.renderer);
    this._NgStyle_1_4 = new import20.NgStyle(this.parentInjector.get(import24.KeyValueDiffers),new import16.ElementRef(this._el_1),this.renderer);
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','ui-grid-row');
    this._text_4 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','ui-orderlist-controls ui-grid-col-2');
    this._text_6 = this.renderer.createText(this._el_5,'\n                    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'icon','fa-angle-up');
    this.renderer.setElementAttribute(this._el_7,'pButton','');
    this.renderer.setElementAttribute(this._el_7,'type','button');
    this._DomHandler_7_3 = new import11.DomHandler();
    this._Button_7_4 = new import3.Button(new import16.ElementRef(this._el_7),this._DomHandler_7_3);
    this._text_8 = this.renderer.createText(this._el_5,'\n                    ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'icon','fa-angle-double-up');
    this.renderer.setElementAttribute(this._el_9,'pButton','');
    this.renderer.setElementAttribute(this._el_9,'type','button');
    this._DomHandler_9_3 = new import11.DomHandler();
    this._Button_9_4 = new import3.Button(new import16.ElementRef(this._el_9),this._DomHandler_9_3);
    this._text_10 = this.renderer.createText(this._el_5,'\n                    ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_11,'icon','fa-angle-down');
    this.renderer.setElementAttribute(this._el_11,'pButton','');
    this.renderer.setElementAttribute(this._el_11,'type','button');
    this._DomHandler_11_3 = new import11.DomHandler();
    this._Button_11_4 = new import3.Button(new import16.ElementRef(this._el_11),this._DomHandler_11_3);
    this._text_12 = this.renderer.createText(this._el_5,'\n                    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_13,'icon','fa-angle-double-down');
    this.renderer.setElementAttribute(this._el_13,'pButton','');
    this.renderer.setElementAttribute(this._el_13,'type','button');
    this._DomHandler_13_3 = new import11.DomHandler();
    this._Button_13_4 = new import3.Button(new import16.ElementRef(this._el_13),this._DomHandler_13_3);
    this._text_14 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._text_15 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','ui-grid-col-10');
    this._text_17 = this.renderer.createText(this._el_16,'\n                    ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._appEl_18 = new import10.AppElement(18,16,this,this._anchor_18);
    this._TemplateRef_18_5 = new import25.TemplateRef_(this._appEl_18,viewFactory_OrderList1);
    this._NgIf_18_6 = new import21.NgIf(this._appEl_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_16,'\n                    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_16,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','ui-widget-content ui-orderlist-list ui-corner-bottom');
    this._NgStyle_20_3 = new import20.NgStyle(this.parentInjector.get(import24.KeyValueDiffers),new import16.ElementRef(this._el_20),this.renderer);
    this._text_21 = this.renderer.createText(this._el_20,'\n                        ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._appEl_22 = new import10.AppElement(22,20,this,this._anchor_22);
    this._TemplateRef_22_5 = new import25.TemplateRef_(this._appEl_22,viewFactory_OrderList2);
    this._NgFor_22_6 = new import22.NgFor(this._appEl_22.vcRef,this._TemplateRef_22_5,this.parentInjector.get(import23.IterableDiffers),this.ref);
    this._text_23 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._text_24 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._text_25 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_26 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._expr_0 = import15.UNINITIALIZED;
    this._map_0 = import13.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'ui-orderlist ui-grid ui-widget': p0,
        'ui-grid-responsive': p1
      }
      ;
    });
    this._expr_1 = import15.UNINITIALIZED;
    this._expr_2 = import15.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_7,'mouseenter',this.eventHandler(this._handle_mouseenter_7_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_7,'mouseleave',this.eventHandler(this._handle_mouseleave_7_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_7,'mousedown',this.eventHandler(this._handle_mousedown_7_3.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_7,'mouseup',this.eventHandler(this._handle_mouseup_7_4.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_7,'focus',this.eventHandler(this._handle_focus_7_5.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_7,'blur',this.eventHandler(this._handle_blur_7_6.bind(this)));
    this._expr_10 = import15.UNINITIALIZED;
    this._expr_11 = import15.UNINITIALIZED;
    this._expr_12 = import15.UNINITIALIZED;
    this._expr_13 = import15.UNINITIALIZED;
    this._expr_14 = import15.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_9,'mouseenter',this.eventHandler(this._handle_mouseenter_9_1.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_9,'mouseleave',this.eventHandler(this._handle_mouseleave_9_2.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_9,'mousedown',this.eventHandler(this._handle_mousedown_9_3.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_9,'mouseup',this.eventHandler(this._handle_mouseup_9_4.bind(this)));
    var disposable_12:Function = this.renderer.listen(this._el_9,'focus',this.eventHandler(this._handle_focus_9_5.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_9,'blur',this.eventHandler(this._handle_blur_9_6.bind(this)));
    this._expr_22 = import15.UNINITIALIZED;
    this._expr_23 = import15.UNINITIALIZED;
    this._expr_24 = import15.UNINITIALIZED;
    this._expr_25 = import15.UNINITIALIZED;
    this._expr_26 = import15.UNINITIALIZED;
    var disposable_14:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    var disposable_15:Function = this.renderer.listen(this._el_11,'mouseenter',this.eventHandler(this._handle_mouseenter_11_1.bind(this)));
    var disposable_16:Function = this.renderer.listen(this._el_11,'mouseleave',this.eventHandler(this._handle_mouseleave_11_2.bind(this)));
    var disposable_17:Function = this.renderer.listen(this._el_11,'mousedown',this.eventHandler(this._handle_mousedown_11_3.bind(this)));
    var disposable_18:Function = this.renderer.listen(this._el_11,'mouseup',this.eventHandler(this._handle_mouseup_11_4.bind(this)));
    var disposable_19:Function = this.renderer.listen(this._el_11,'focus',this.eventHandler(this._handle_focus_11_5.bind(this)));
    var disposable_20:Function = this.renderer.listen(this._el_11,'blur',this.eventHandler(this._handle_blur_11_6.bind(this)));
    this._expr_34 = import15.UNINITIALIZED;
    this._expr_35 = import15.UNINITIALIZED;
    this._expr_36 = import15.UNINITIALIZED;
    this._expr_37 = import15.UNINITIALIZED;
    this._expr_38 = import15.UNINITIALIZED;
    var disposable_21:Function = this.renderer.listen(this._el_13,'click',this.eventHandler(this._handle_click_13_0.bind(this)));
    var disposable_22:Function = this.renderer.listen(this._el_13,'mouseenter',this.eventHandler(this._handle_mouseenter_13_1.bind(this)));
    var disposable_23:Function = this.renderer.listen(this._el_13,'mouseleave',this.eventHandler(this._handle_mouseleave_13_2.bind(this)));
    var disposable_24:Function = this.renderer.listen(this._el_13,'mousedown',this.eventHandler(this._handle_mousedown_13_3.bind(this)));
    var disposable_25:Function = this.renderer.listen(this._el_13,'mouseup',this.eventHandler(this._handle_mouseup_13_4.bind(this)));
    var disposable_26:Function = this.renderer.listen(this._el_13,'focus',this.eventHandler(this._handle_focus_13_5.bind(this)));
    var disposable_27:Function = this.renderer.listen(this._el_13,'blur',this.eventHandler(this._handle_blur_13_6.bind(this)));
    this._expr_46 = import15.UNINITIALIZED;
    this._expr_47 = import15.UNINITIALIZED;
    this._expr_48 = import15.UNINITIALIZED;
    this._expr_49 = import15.UNINITIALIZED;
    this._expr_50 = import15.UNINITIALIZED;
    this._expr_51 = import15.UNINITIALIZED;
    this._expr_52 = import15.UNINITIALIZED;
    this._expr_53 = import15.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15,
      disposable_16,
      disposable_17,
      disposable_18,
      disposable_19,
      disposable_20,
      disposable_21,
      disposable_22,
      disposable_23,
      disposable_24,
      disposable_25,
      disposable_26,
      disposable_27
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.DomHandler) && (7 === requestNodeIndex))) { return this._DomHandler_7_3; }
    if (((token === import3.Button) && (7 === requestNodeIndex))) { return this._Button_7_4; }
    if (((token === import11.DomHandler) && (9 === requestNodeIndex))) { return this._DomHandler_9_3; }
    if (((token === import3.Button) && (9 === requestNodeIndex))) { return this._Button_9_4; }
    if (((token === import11.DomHandler) && (11 === requestNodeIndex))) { return this._DomHandler_11_3; }
    if (((token === import3.Button) && (11 === requestNodeIndex))) { return this._Button_11_4; }
    if (((token === import11.DomHandler) && (13 === requestNodeIndex))) { return this._DomHandler_13_3; }
    if (((token === import3.Button) && (13 === requestNodeIndex))) { return this._Button_13_4; }
    if (((token === import25.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import21.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6; }
    if (((token === import25.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import22.NgFor) && (22 === requestNodeIndex))) { return this._NgFor_22_6; }
    if (((token === import20.NgStyle) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._NgStyle_20_3; }
    if (((token === import19.NgClass) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgClass_1_3; }
    if (((token === import20.NgStyle) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgStyle_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import15.SimpleChange} = (null as any);
    const currVal_0:any = this.context.styleClass;
    if (import13.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgClass_1_3.klass = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._map_0(true,this.context.responsive);
    if (import13.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_1_3.ngClass = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgClass_1_3.ngDoCheck(); }
    const currVal_2:any = this.context.style;
    if (import13.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgStyle_1_4.ngStyle = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgStyle_1_4.ngDoCheck(); }
    const currVal_10:any = 'fa-angle-up';
    if (import13.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Button_7_4.icon = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_22:any = 'fa-angle-double-up';
    if (import13.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._Button_9_4.icon = currVal_22;
      this._expr_22 = currVal_22;
    }
    const currVal_34:any = 'fa-angle-down';
    if (import13.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._Button_11_4.icon = currVal_34;
      this._expr_34 = currVal_34;
    }
    const currVal_46:any = 'fa-angle-double-down';
    if (import13.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this._Button_13_4.icon = currVal_46;
      this._expr_46 = currVal_46;
    }
    const currVal_51:any = this.context.header;
    if (import13.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this._NgIf_18_6.ngIf = currVal_51;
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this.context.listStyle;
    if (import13.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this._NgStyle_20_3.ngStyle = currVal_52;
      this._expr_52 = currVal_52;
    }
    if (!throwOnChange) { this._NgStyle_20_3.ngDoCheck(); }
    changes = (null as any);
    const currVal_53:any = this.context.value;
    if (import13.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this._NgFor_22_6.ngForOf = currVal_53;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import15.SimpleChange(this._expr_53,currVal_53);
      this._expr_53 = currVal_53;
    }
    if ((changes !== (null as any))) { this._NgFor_22_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_22_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_11:any = (this._Button_7_4.hover && !this._Button_7_4.isDisabled());
    if (import13.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_7,'ui-state-hover',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._Button_7_4.focus;
    if (import13.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_7,'ui-state-focus',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._Button_7_4.active;
    if (import13.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_7,'ui-state-active',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._Button_7_4.isDisabled();
    if (import13.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_7,'ui-state-disabled',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_23:any = (this._Button_9_4.hover && !this._Button_9_4.isDisabled());
    if (import13.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_9,'ui-state-hover',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._Button_9_4.focus;
    if (import13.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_9,'ui-state-focus',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._Button_9_4.active;
    if (import13.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_9,'ui-state-active',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._Button_9_4.isDisabled();
    if (import13.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_9,'ui-state-disabled',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_35:any = (this._Button_11_4.hover && !this._Button_11_4.isDisabled());
    if (import13.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_11,'ui-state-hover',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._Button_11_4.focus;
    if (import13.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_11,'ui-state-focus',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._Button_11_4.active;
    if (import13.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_11,'ui-state-active',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._Button_11_4.isDisabled();
    if (import13.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_11,'ui-state-disabled',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_47:any = (this._Button_13_4.hover && !this._Button_13_4.isDisabled());
    if (import13.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_13,'ui-state-hover',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._Button_13_4.focus;
    if (import13.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_13,'ui-state-focus',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._Button_13_4.active;
    if (import13.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_13,'ui-state-active',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = this._Button_13_4.isDisabled();
    if (import13.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_13,'ui-state-disabled',currVal_50);
      this._expr_50 = currVal_50;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_7_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_9_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_11_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_13_4.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Button_7_4.ngOnDestroy();
    this._Button_9_4.ngOnDestroy();
    this._Button_11_4.ngOnDestroy();
    this._Button_13_4.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.moveUp($event,this._el_20)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_7_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_7_4.onMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_7_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_7_4.onMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_7_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_7_4.onMouseDown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_7_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_7_4.onMouseUp($event)) !== false);
    return (true && pd_0);
  }
  private _handle_focus_7_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_7_4.onFocus($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_7_6($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_7_4.onBlur($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.moveTop($event,this._el_20)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_9_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_9_4.onMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_9_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_9_4.onMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_9_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_9_4.onMouseDown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_9_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_9_4.onMouseUp($event)) !== false);
    return (true && pd_0);
  }
  private _handle_focus_9_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_9_4.onFocus($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_9_6($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_9_4.onBlur($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.moveDown($event,this._el_20)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_11_4.onMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_11_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_11_4.onMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_11_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_11_4.onMouseDown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_11_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_11_4.onMouseUp($event)) !== false);
    return (true && pd_0);
  }
  private _handle_focus_11_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_11_4.onFocus($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_11_6($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_11_4.onBlur($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.moveBottom($event,this._el_20)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_13_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_13_4.onMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_13_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_13_4.onMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_13_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_13_4.onMouseDown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_13_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_13_4.onMouseUp($event)) !== false);
    return (true && pd_0);
  }
  private _handle_focus_13_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_13_4.onFocus($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_13_6($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_13_4.onBlur($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_OrderList0(viewUtils:import13.ViewUtils,parentInjector:import6.Injector,declarationEl:import10.AppElement):import9.AppView<import1.OrderList> {
  if ((renderType_OrderList === (null as any))) { (renderType_OrderList = viewUtils.createRenderComponentType('c:/Users/eirwn/Documents/primeng-min/components/orderlist/orderlist.ts class OrderList - inline template',0,import17.ViewEncapsulation.None,styles_OrderList,{})); }
  return new _View_OrderList0(viewUtils,parentInjector,declarationEl);
}
class _View_OrderList1 extends import9.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import13.ViewUtils,parentInjector:import6.Injector,declarationEl:import10.AppElement) {
    super(_View_OrderList1,renderType_OrderList,import14.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import15.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import10.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-orderlist-caption ui-widget-header ui-corner-top');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import15.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import13.interpolate(1,'',this.parent.context.header,'');
    if (import13.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_OrderList1(viewUtils:import13.ViewUtils,parentInjector:import6.Injector,declarationEl:import10.AppElement):import9.AppView<any> {
  return new _View_OrderList1(viewUtils,parentInjector,declarationEl);
}
class _View_OrderList2 extends import9.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import19.NgClass;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import10.AppElement;
  _TemplateRef_2_5:any;
  _TemplateWrapper_2_6:import4.TemplateWrapper;
  _text_3:any;
  _map_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import13.ViewUtils,parentInjector:import6.Injector,declarationEl:import10.AppElement) {
    super(_View_OrderList2,renderType_OrderList,import14.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import15.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import10.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._NgClass_0_3 = new import19.NgClass(this.parent.parentInjector.get(import23.IterableDiffers),this.parent.parentInjector.get(import24.KeyValueDiffers),new import16.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import10.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import25.TemplateRef_(this._appEl_2,viewFactory_OrderList3);
    this._TemplateWrapper_2_6 = new import4.TemplateWrapper(this._appEl_2.vcRef);
    this._text_3 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'mouseenter',this.eventHandler(this._handle_mouseenter_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'mouseleave',this.eventHandler(this._handle_mouseleave_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_2.bind(this)));
    this._map_0 = import13.pureProxy3((p0:any,p1:any,p2:any):{[key: string]:any} => {
      return {
        'ui-orderlist-item': p0,
        'ui-state-hover': p1,
        'ui-state-highlight': p2
      }
      ;
    });
    this._expr_3 = import15.UNINITIALIZED;
    this._expr_4 = import15.UNINITIALIZED;
    this._expr_5 = import15.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import4.TemplateWrapper) && (2 === requestNodeIndex))) { return this._TemplateWrapper_2_6; }
    if (((token === import19.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgClass_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = this._map_0(true,(this.parent.context.hoveredItem == this.context.$implicit),this.parent.context.isSelected(this.context.$implicit));
    if (import13.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgClass_0_3.ngClass = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (!throwOnChange) { this._NgClass_0_3.ngDoCheck(); }
    const currVal_4:any = this.context.$implicit;
    if (import13.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._TemplateWrapper_2_6.item = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.parent.context.itemTemplate;
    if (import13.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._TemplateWrapper_2_6.templateRef = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TemplateWrapper_2_6.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_mouseenter_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.hoveredItem = this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.hoveredItem = (null as any))) !== false);
    return (true && pd_0);
  }
  private _handle_click_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onItemClick($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_OrderList2(viewUtils:import13.ViewUtils,parentInjector:import6.Injector,declarationEl:import10.AppElement):import9.AppView<any> {
  return new _View_OrderList2(viewUtils,parentInjector,declarationEl);
}
class _View_OrderList3 extends import9.AppView<any> {
  constructor(viewUtils:import13.ViewUtils,parentInjector:import6.Injector,declarationEl:import10.AppElement) {
    super(_View_OrderList3,renderType_OrderList,import14.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import15.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import10.AppElement {
    this.init([],[],[],[]);
    return (null as any);
  }
}
function viewFactory_OrderList3(viewUtils:import13.ViewUtils,parentInjector:import6.Injector,declarationEl:import10.AppElement):import9.AppView<any> {
  return new _View_OrderList3(viewUtils,parentInjector,declarationEl);
}