/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../components/carousel/carousel';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '../../../components/common/shared';
import * as import4 from '@angular/common/src/localization';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/i18n/tokens';
import * as import7 from '@angular/core/src/render/api';
import * as import8 from '@angular/core/src/linker/view';
import * as import9 from '@angular/core/src/linker/element';
import * as import10 from '../../../components/dom/domhandler';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/core/src/linker/view_utils';
import * as import13 from '@angular/core/src/linker/view_type';
import * as import14 from '@angular/core/src/change_detection/change_detection';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/core/src/metadata/view';
import * as import18 from '@angular/core/src/linker/component_factory';
import * as import19 from '@angular/common/src/directives/ng_class';
import * as import20 from '@angular/common/src/directives/ng_style';
import * as import21 from '@angular/common/src/directives/ng_if';
import * as import22 from '@angular/common/src/directives/ng_for';
import * as import23 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import24 from '@angular/core/src/linker/template_ref';
import * as import25 from '@angular/core/src/security';
class CarouselModuleInjector extends import0.NgModuleInjector<import1.CarouselModule> {
  _CommonModule_0:import2.CommonModule;
  _SharedModule_1:import3.SharedModule;
  _CarouselModule_2:import1.CarouselModule;
  __LOCALE_ID_3:any;
  __NgLocalization_4:import4.NgLocaleLocalization;
  __TRANSLATIONS_FORMAT_5:any;
  constructor(parent:import5.Injector) {
    super(parent,[],[]);
  }
  get _LOCALE_ID_3():any {
    if ((this.__LOCALE_ID_3 == (null as any))) { (this.__LOCALE_ID_3 = (null as any)); }
    return this.__LOCALE_ID_3;
  }
  get _NgLocalization_4():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == (null as any))) { (this.__NgLocalization_4 = new import4.NgLocaleLocalization(this._LOCALE_ID_3)); }
    return this.__NgLocalization_4;
  }
  get _TRANSLATIONS_FORMAT_5():any {
    if ((this.__TRANSLATIONS_FORMAT_5 == (null as any))) { (this.__TRANSLATIONS_FORMAT_5 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_5;
  }
  createInternal():import1.CarouselModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._SharedModule_1 = new import3.SharedModule();
    this._CarouselModule_2 = new import1.CarouselModule();
    return this._CarouselModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.SharedModule)) { return this._SharedModule_1; }
    if ((token === import1.CarouselModule)) { return this._CarouselModule_2; }
    if ((token === import6.LOCALE_ID)) { return this._LOCALE_ID_3; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import6.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CarouselModuleNgFactory:import0.NgModuleFactory<import1.CarouselModule> = new import0.NgModuleFactory(CarouselModuleInjector,import1.CarouselModule);
var renderType_Carousel_Host:import7.RenderComponentType = (null as any);
class _View_Carousel_Host0 extends import8.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import9.AppElement;
  _DomHandler_0_4:import10.DomHandler;
  _Carousel_0_5:import1.Carousel;
  _query_TemplateRef_0_0:import11.QueryList<any>;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Carousel_Host0,renderType_Carousel_Host,import13.ViewType.HOST,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.selectOrCreateHostElement('p-carousel',rootSelector,(null as any));
    this._appEl_0 = new import9.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Carousel0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DomHandler_0_4 = new import10.DomHandler();
    this._Carousel_0_5 = new import1.Carousel(new import15.ElementRef(this._el_0),this._DomHandler_0_4,this.parentInjector.get(import16.IterableDiffers),this.renderer);
    this._query_TemplateRef_0_0 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Carousel_0_5,[],compView_0);
    this._query_TemplateRef_0_0.reset([]);
    this._Carousel_0_5.itemTemplate = this._query_TemplateRef_0_0.first;
    compView_0.create(this._Carousel_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.DomHandler) && (0 === requestNodeIndex))) { return this._DomHandler_0_4; }
    if (((token === import1.Carousel) && (0 === requestNodeIndex))) { return this._Carousel_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Carousel_0_5.ngOnInit(); }
    if (!throwOnChange) { this._Carousel_0_5.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Carousel_0_5.ngAfterViewInit(); }
      this._Carousel_0_5.ngAfterViewChecked();
    }
  }
  destroyInternal():void {
    this._Carousel_0_5.ngOnDestroy();
  }
}
function viewFactory_Carousel_Host0(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  if ((renderType_Carousel_Host === (null as any))) { (renderType_Carousel_Host = viewUtils.createRenderComponentType('',0,import17.ViewEncapsulation.None,[],{})); }
  return new _View_Carousel_Host0(viewUtils,parentInjector,declarationEl);
}
export const CarouselNgFactory:import18.ComponentFactory<import1.Carousel> = new import18.ComponentFactory<import1.Carousel>('p-carousel',viewFactory_Carousel_Host0,import1.Carousel);
const styles_Carousel:any[] = [];
var renderType_Carousel:import7.RenderComponentType = (null as any);
class _View_Carousel0 extends import8.AppView<import1.Carousel> {
  _text_0:any;
  _el_1:any;
  _NgClass_1_3:import19.NgClass;
  _NgStyle_1_4:import20.NgStyle;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _NgClass_8_3:import19.NgClass;
  _text_9:any;
  _el_10:any;
  _NgClass_10_3:import19.NgClass;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _appEl_12:import9.AppElement;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import21.NgIf;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _appEl_14:import9.AppElement;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import21.NgIf;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import9.AppElement;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import21.NgIf;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import9.AppElement;
  _TemplateRef_23_5:any;
  _NgFor_23_6:import22.NgFor;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  /*private*/ _expr_0:any;
  _map_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  _map_1:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  _map_2:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Carousel0,renderType_Carousel,import13.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._NgClass_1_3 = new import19.NgClass(this.parentInjector.get(import16.IterableDiffers),this.parentInjector.get(import23.KeyValueDiffers),new import15.ElementRef(this._el_1),this.renderer);
    this._NgStyle_1_4 = new import20.NgStyle(this.parentInjector.get(import23.KeyValueDiffers),new import15.ElementRef(this._el_1),this.renderer);
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','ui-carousel-header ui-widget-header');
    this._text_4 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','ui-carousel-header-title');
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_3,'span',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','ui-carousel-button ui-carousel-next-button fa fa-arrow-circle-right');
    this._NgClass_8_3 = new import19.NgClass(this.parentInjector.get(import16.IterableDiffers),this.parentInjector.get(import23.KeyValueDiffers),new import15.ElementRef(this._el_8),this.renderer);
    this._text_9 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_3,'span',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','ui-carousel-button ui-carousel-prev-button fa fa-arrow-circle-left');
    this._NgClass_10_3 = new import19.NgClass(this.parentInjector.get(import16.IterableDiffers),this.parentInjector.get(import23.KeyValueDiffers),new import15.ElementRef(this._el_10),this.renderer);
    this._text_11 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_12 = new import9.AppElement(12,3,this,this._anchor_12);
    this._TemplateRef_12_5 = new import24.TemplateRef_(this._appEl_12,viewFactory_Carousel1);
    this._NgIf_12_6 = new import21.NgIf(this._appEl_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_14 = new import9.AppElement(14,3,this,this._anchor_14);
    this._TemplateRef_14_5 = new import24.TemplateRef_(this._appEl_14,viewFactory_Carousel3);
    this._NgIf_14_6 = new import21.NgIf(this._appEl_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_16 = new import9.AppElement(16,3,this,this._anchor_16);
    this._TemplateRef_16_5 = new import24.TemplateRef_(this._appEl_16,viewFactory_Carousel5);
    this._NgIf_16_6 = new import21.NgIf(this._appEl_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_18 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','ui-carousel-viewport');
    this._text_20 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','ui-carousel-items');
    this._text_22 = this.renderer.createText(this._el_21,'\n                    ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_21,(null as any));
    this._appEl_23 = new import9.AppElement(23,21,this,this._anchor_23);
    this._TemplateRef_23_5 = new import24.TemplateRef_(this._appEl_23,viewFactory_Carousel7);
    this._NgFor_23_6 = new import22.NgFor(this._appEl_23.vcRef,this._TemplateRef_23_5,this.parentInjector.get(import16.IterableDiffers),this.ref);
    this._text_24 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._text_25 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._text_26 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._expr_0 = import14.UNINITIALIZED;
    this._map_0 = import12.pureProxy1((p0:any):{[key: string]:any} => {
      return {'ui-carousel ui-widget ui-widget-content ui-corner-all': p0};
    });
    this._expr_1 = import14.UNINITIALIZED;
    this._expr_2 = import14.UNINITIALIZED;
    this._expr_3 = import14.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._expr_5 = import14.UNINITIALIZED;
    this._map_1 = import12.pureProxy1((p0:any):{[key: string]:any} => {
      return {'ui-state-disabled': p0};
    });
    this._expr_6 = import14.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    this._expr_8 = import14.UNINITIALIZED;
    this._map_2 = import12.pureProxy1((p0:any):{[key: string]:any} => {
      return {'ui-state-disabled': p0};
    });
    this._expr_9 = import14.UNINITIALIZED;
    this._expr_10 = import14.UNINITIALIZED;
    this._expr_11 = import14.UNINITIALIZED;
    this._expr_12 = import14.UNINITIALIZED;
    this._expr_13 = import14.UNINITIALIZED;
    this._expr_14 = import14.UNINITIALIZED;
    this._expr_15 = import14.UNINITIALIZED;
    this._expr_16 = import14.UNINITIALIZED;
    this._expr_17 = import14.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.NgClass) && (8 === requestNodeIndex))) { return this._NgClass_8_3; }
    if (((token === import19.NgClass) && (10 === requestNodeIndex))) { return this._NgClass_10_3; }
    if (((token === import24.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import21.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6; }
    if (((token === import24.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import21.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6; }
    if (((token === import24.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import21.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6; }
    if (((token === import24.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import22.NgFor) && (23 === requestNodeIndex))) { return this._NgFor_23_6; }
    if (((token === import19.NgClass) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgClass_1_3; }
    if (((token === import20.NgStyle) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgStyle_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import14.SimpleChange} = (null as any);
    const currVal_0:any = this.context.styleClass;
    if (import12.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgClass_1_3.klass = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._map_0(true);
    if (import12.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_1_3.ngClass = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgClass_1_3.ngDoCheck(); }
    const currVal_2:any = this.context.style;
    if (import12.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgStyle_1_4.ngStyle = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgStyle_1_4.ngDoCheck(); }
    const currVal_5:any = 'ui-carousel-button ui-carousel-next-button fa fa-arrow-circle-right';
    if (import12.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgClass_8_3.klass = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._map_1(((this.context.page === (this.context.totalPages - 1)) && !this.context.circular));
    if (import12.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgClass_8_3.ngClass = currVal_6;
      this._expr_6 = currVal_6;
    }
    if (!throwOnChange) { this._NgClass_8_3.ngDoCheck(); }
    const currVal_8:any = 'ui-carousel-button ui-carousel-prev-button fa fa-arrow-circle-left';
    if (import12.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgClass_10_3.klass = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._map_2(((this.context.page === 0) && !this.context.circular));
    if (import12.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgClass_10_3.ngClass = currVal_9;
      this._expr_9 = currVal_9;
    }
    if (!throwOnChange) { this._NgClass_10_3.ngDoCheck(); }
    const currVal_10:any = this.context.displayPageLinks;
    if (import12.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgIf_12_6.ngIf = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this.context.displayPageDropdown;
    if (import12.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgIf_14_6.ngIf = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this.context.responsive;
    if (import12.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgIf_16_6.ngIf = currVal_12;
      this._expr_12 = currVal_12;
    }
    changes = (null as any);
    const currVal_17:any = this.context.value;
    if (import12.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._NgFor_23_6.ngForOf = currVal_17;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import14.SimpleChange(this._expr_17,currVal_17);
      this._expr_17 = currVal_17;
    }
    if ((changes !== (null as any))) { this._NgFor_23_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_23_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = import12.interpolate(1,'',this.context.headerText,'');
    if (import12.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_6,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_13:any = this.context.left;
    if (import12.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementStyle(this._el_21,'left',((this.viewUtils.sanitizer.sanitize(import25.SecurityContext.STYLE,currVal_13) == (null as any))? (null as any): (this.viewUtils.sanitizer.sanitize(import25.SecurityContext.STYLE,currVal_13).toString() + 'px')));
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = 'left';
    if (import12.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementStyle(this._el_21,'transitionProperty',((this.viewUtils.sanitizer.sanitize(import25.SecurityContext.STYLE,currVal_14) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import25.SecurityContext.STYLE,currVal_14).toString()));
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.context.effectDuration;
    if (import12.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementStyle(this._el_21,'transitionDuration',((this.viewUtils.sanitizer.sanitize(import25.SecurityContext.STYLE,currVal_15) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import25.SecurityContext.STYLE,currVal_15).toString()));
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this.context.easing;
    if (import12.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementStyle(this._el_21,'transitionTimingFunction',((this.viewUtils.sanitizer.sanitize(import25.SecurityContext.STYLE,currVal_16) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import25.SecurityContext.STYLE,currVal_16).toString()));
      this._expr_16 = currVal_16;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onNextNav()) !== false);
    return (true && pd_0);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onPrevNav()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Carousel0(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<import1.Carousel> {
  if ((renderType_Carousel === (null as any))) { (renderType_Carousel = viewUtils.createRenderComponentType('c:/Users/eirwn/Documents/primeng-min/components/carousel/carousel.ts class Carousel - inline template',0,import17.ViewEncapsulation.None,styles_Carousel,{})); }
  return new _View_Carousel0(viewUtils,parentInjector,declarationEl);
}
class _View_Carousel1 extends import8.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import9.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import22.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Carousel1,renderType_Carousel,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-carousel-page-links');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import9.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import24.TemplateRef_(this._appEl_2,viewFactory_Carousel2);
    this._NgFor_2_6 = new import22.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import16.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_0 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import22.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import14.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.anchorPageLinks;
    if (import12.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import14.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Carousel1(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Carousel1(viewUtils,parentInjector,declarationEl);
}
class _View_Carousel2 extends import8.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import19.NgClass;
  /*private*/ _expr_1:any;
  _map_0:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Carousel2,renderType_Carousel,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-carousel-page-link fa fa-circle-o');
    this.renderer.setElementAttribute(this._el_0,'href','#');
    this._NgClass_0_3 = new import19.NgClass(this.parent.parent.parentInjector.get(import16.IterableDiffers),this.parent.parent.parentInjector.get(import23.KeyValueDiffers),new import15.ElementRef(this._el_0),this.renderer);
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import14.UNINITIALIZED;
    this._map_0 = import12.pureProxy1((p0:any):{[key: string]:any} => {
      return {'fa-dot-circle-o': p0};
    });
    this._expr_2 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.NgClass) && (0 === requestNodeIndex))) { return this._NgClass_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'ui-carousel-page-link fa fa-circle-o';
    if (import12.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_0_3.klass = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._map_0((this.parent.parent.context.page === this.context.index));
    if (import12.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_0_3.ngClass = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgClass_0_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.setPageWithLink($event,this.context.index)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Carousel2(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Carousel2(viewUtils,parentInjector,declarationEl);
}
class _View_Carousel3 extends import8.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import9.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import22.NgFor;
  _text_3:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Carousel3,renderType_Carousel,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'select',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-carousel-dropdown ui-widget ui-state-default ui-corner-left');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import9.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import24.TemplateRef_(this._appEl_2,viewFactory_Carousel4);
    this._NgFor_2_6 = new import22.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import16.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_1 = import14.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'change',this.eventHandler(this._handle_change_0_0.bind(this)));
    this._expr_2 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import22.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import14.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = this.parent.context.selectDropdownOptions;
    if (import12.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgFor_2_6.ngForOf = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import14.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.parent.context.page;
    if (import12.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'value',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_change_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onDropdownChange($event.target.value)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Carousel3(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Carousel3(viewUtils,parentInjector,declarationEl);
}
class _View_Carousel4 extends import8.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Carousel4,renderType_Carousel,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'option',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import14.UNINITIALIZED;
    this._expr_1 = import14.UNINITIALIZED;
    this._expr_2 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.context.$implicit;
    if (import12.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'value',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.parent.parent.context.value == this.context.$implicit);
    if (import12.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'selected',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import12.interpolate(1,'',(this.context.$implicit + 1),'');
    if (import12.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Carousel4(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Carousel4(viewUtils,parentInjector,declarationEl);
}
class _View_Carousel5 extends import8.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import9.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import22.NgFor;
  _text_3:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Carousel5,renderType_Carousel,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'select',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-carousel-mobiledropdown ui-widget ui-state-default ui-corner-left');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import9.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import24.TemplateRef_(this._appEl_2,viewFactory_Carousel6);
    this._NgFor_2_6 = new import22.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import16.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_1 = import14.UNINITIALIZED;
    this._expr_2 = import14.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'change',this.eventHandler(this._handle_change_0_0.bind(this)));
    this._expr_3 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import22.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import14.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = this.parent.context.mobileDropdownOptions;
    if (import12.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgFor_2_6.ngForOf = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import14.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.parent.context.page;
    if (import12.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'value',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = (this.parent.context.shrinked? 'block': 'none');
    if (import12.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementStyle(this._el_0,'display',((this.viewUtils.sanitizer.sanitize(import25.SecurityContext.STYLE,currVal_2) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import25.SecurityContext.STYLE,currVal_2).toString()));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_change_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onDropdownChange($event.target.value)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Carousel5(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Carousel5(viewUtils,parentInjector,declarationEl);
}
class _View_Carousel6 extends import8.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Carousel6,renderType_Carousel,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'option',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import14.UNINITIALIZED;
    this._expr_1 = import14.UNINITIALIZED;
    this._expr_2 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.context.$implicit;
    if (import12.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'value',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.parent.parent.context.value == this.context.$implicit);
    if (import12.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'selected',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import12.interpolate(1,'',(this.context.$implicit + 1),'');
    if (import12.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Carousel6(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Carousel6(viewUtils,parentInjector,declarationEl);
}
class _View_Carousel7 extends import8.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import9.AppElement;
  _TemplateRef_2_5:any;
  _TemplateWrapper_2_6:import3.TemplateWrapper;
  _text_3:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Carousel7,renderType_Carousel,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-carousel-item ui-widget-content ui-corner-all');
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import9.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import24.TemplateRef_(this._appEl_2,viewFactory_Carousel8);
    this._TemplateWrapper_2_6 = new import3.TemplateWrapper(this._appEl_2.vcRef);
    this._text_3 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._expr_0 = import14.UNINITIALIZED;
    this._expr_1 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import3.TemplateWrapper) && (2 === requestNodeIndex))) { return this._TemplateWrapper_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import12.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._TemplateWrapper_2_6.item = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.itemTemplate;
    if (import12.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._TemplateWrapper_2_6.templateRef = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TemplateWrapper_2_6.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Carousel7(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Carousel7(viewUtils,parentInjector,declarationEl);
}
class _View_Carousel8 extends import8.AppView<any> {
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Carousel8,renderType_Carousel,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this.init([],[],[],[]);
    return (null as any);
  }
}
function viewFactory_Carousel8(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Carousel8(viewUtils,parentInjector,declarationEl);
}