/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../components/dialog/dialog';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '../../../components/common/shared';
import * as import4 from '@angular/common/src/localization';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/i18n/tokens';
import * as import7 from '@angular/core/src/render/api';
import * as import8 from '@angular/core/src/linker/view';
import * as import9 from '@angular/core/src/linker/element';
import * as import10 from '../../../components/dom/domhandler';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/core/src/linker/view_utils';
import * as import13 from '@angular/core/src/linker/view_type';
import * as import14 from '@angular/core/src/change_detection/change_detection';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/core/src/metadata/view';
import * as import17 from '@angular/core/src/linker/component_factory';
import * as import18 from '@angular/core/src/animation/animation_style_util';
import * as import19 from '@angular/core/src/animation/animation_sequence_player';
import * as import20 from '@angular/core/src/animation/animation_styles';
import * as import21 from '@angular/core/src/animation/animation_keyframe';
import * as import22 from '@angular/core/src/animation/animation_player';
import * as import23 from '@angular/common/src/directives/ng_class';
import * as import24 from '@angular/common/src/directives/ng_if';
import * as import25 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import26 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import27 from '@angular/core/src/linker/template_ref';
import * as import28 from '@angular/core/src/security';
class DialogModuleInjector extends import0.NgModuleInjector<import1.DialogModule> {
  _CommonModule_0:import2.CommonModule;
  _SharedModule_1:import3.SharedModule;
  _DialogModule_2:import1.DialogModule;
  __LOCALE_ID_3:any;
  __NgLocalization_4:import4.NgLocaleLocalization;
  __TRANSLATIONS_FORMAT_5:any;
  constructor(parent:import5.Injector) {
    super(parent,[],[]);
  }
  get _LOCALE_ID_3():any {
    if ((this.__LOCALE_ID_3 == (null as any))) { (this.__LOCALE_ID_3 = (null as any)); }
    return this.__LOCALE_ID_3;
  }
  get _NgLocalization_4():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == (null as any))) { (this.__NgLocalization_4 = new import4.NgLocaleLocalization(this._LOCALE_ID_3)); }
    return this.__NgLocalization_4;
  }
  get _TRANSLATIONS_FORMAT_5():any {
    if ((this.__TRANSLATIONS_FORMAT_5 == (null as any))) { (this.__TRANSLATIONS_FORMAT_5 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_5;
  }
  createInternal():import1.DialogModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._SharedModule_1 = new import3.SharedModule();
    this._DialogModule_2 = new import1.DialogModule();
    return this._DialogModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.SharedModule)) { return this._SharedModule_1; }
    if ((token === import1.DialogModule)) { return this._DialogModule_2; }
    if ((token === import6.LOCALE_ID)) { return this._LOCALE_ID_3; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import6.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DialogModuleNgFactory:import0.NgModuleFactory<import1.DialogModule> = new import0.NgModuleFactory(DialogModuleInjector,import1.DialogModule);
var renderType_Dialog_Host:import7.RenderComponentType = (null as any);
class _View_Dialog_Host0 extends import8.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import9.AppElement;
  _DomHandler_0_4:import10.DomHandler;
  _Dialog_0_5:import1.Dialog;
  _query_Header_0_0:import11.QueryList<any>;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Dialog_Host0,renderType_Dialog_Host,import13.ViewType.HOST,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.selectOrCreateHostElement('p-dialog',rootSelector,(null as any));
    this._appEl_0 = new import9.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Dialog0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DomHandler_0_4 = new import10.DomHandler();
    this._Dialog_0_5 = new import1.Dialog(new import15.ElementRef(this._el_0),this._DomHandler_0_4,this.renderer);
    this._query_Header_0_0 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Dialog_0_5,[],compView_0);
    this._query_Header_0_0.reset([]);
    this._Dialog_0_5.headerFacet = this._query_Header_0_0.first;
    compView_0.create(this._Dialog_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.DomHandler) && (0 === requestNodeIndex))) { return this._DomHandler_0_4; }
    if (((token === import1.Dialog) && (0 === requestNodeIndex))) { return this._Dialog_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Dialog_0_5.ngAfterViewInit(); }
      this._Dialog_0_5.ngAfterViewChecked();
    }
  }
  destroyInternal():void {
    this._Dialog_0_5.ngOnDestroy();
  }
}
function viewFactory_Dialog_Host0(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  if ((renderType_Dialog_Host === (null as any))) { (renderType_Dialog_Host = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,[],{})); }
  return new _View_Dialog_Host0(viewUtils,parentInjector,declarationEl);
}
export const DialogNgFactory:import17.ComponentFactory<import1.Dialog> = new import17.ComponentFactory<import1.Dialog>('p-dialog',viewFactory_Dialog_Host0,import1.Dialog);
const styles_Dialog:any[] = [];
var Dialog_dialogState_states:any = {
  hidden: {opacity: 0},
  visible: {opacity: 1},
  '*': {}
}
;
function Dialog_dialogState_factory(view:import8.AppView<any>,element:any,currentState:any,nextState:any):void {
  view.cancelActiveAnimation(element,'dialogState',(nextState == 'void'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = Dialog_dialogState_states['*'];
  var startStateStyles:any = Dialog_dialogState_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = Dialog_dialogState_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  import18.renderStyles(element,view.renderer,import18.clearStyles(startStateStyles));
  if (((player == (null as any)) && ((currentState == 'visible') && (nextState == 'hidden')))) {
      player = new import19.AnimationSequencePlayer([view.renderer.animate(element,new import20.AnimationStyles(import18.collectAndResolveStyles(collectedStyles,[startStateStyles])),import18.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import21.AnimationKeyframe(0,new import20.AnimationStyles(import18.collectAndResolveStyles(collectedStyles,[{}]))),
        new import21.AnimationKeyframe(1,new import20.AnimationStyles(import18.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),400,0,'ease-in')]);
    totalTime = 400;
  }
  if (((player == (null as any)) && ((currentState == 'hidden') && (nextState == 'visible')))) {
      player = new import19.AnimationSequencePlayer([view.renderer.animate(element,new import20.AnimationStyles(import18.collectAndResolveStyles(collectedStyles,[startStateStyles])),import18.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import21.AnimationKeyframe(0,new import20.AnimationStyles(import18.collectAndResolveStyles(collectedStyles,[{}]))),
        new import21.AnimationKeyframe(1,new import20.AnimationStyles(import18.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),400,0,'ease-out')]);
    totalTime = 400;
  }
  if ((player == (null as any))) { (player = new import22.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    import18.renderStyles(element,view.renderer,import18.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  view.queueAnimation(element,'dialogState',player,totalTime,currentState,nextState);
}
var renderType_Dialog:import7.RenderComponentType = (null as any);
class _View_Dialog0 extends import8.AppView<import1.Dialog> {
  _text_0:any;
  _el_1:any;
  _NgClass_1_3:import23.NgClass;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _appEl_5:import9.AppElement;
  _TemplateRef_5_5:any;
  _NgIf_5_6:import24.NgIf;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import9.AppElement;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import24.NgIf;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import9.AppElement;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import24.NgIf;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import9.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import24.NgIf;
  _text_18:any;
  _text_19:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _map_0:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Dialog0,renderType_Dialog,import13.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._NgClass_1_3 = new import23.NgClass(this.parentInjector.get(import25.IterableDiffers),this.parentInjector.get(import26.KeyValueDiffers),new import15.ElementRef(this._el_1),this.renderer);
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-corner-top');
    this._text_4 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_5 = new import9.AppElement(5,3,this,this._anchor_5);
    this._TemplateRef_5_5 = new import27.TemplateRef_(this._appEl_5,viewFactory_Dialog1);
    this._NgIf_5_6 = new import24.NgIf(this._appEl_5.vcRef,this._TemplateRef_5_5);
    this._text_6 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_7 = new import9.AppElement(7,3,this,this._anchor_7);
    this._TemplateRef_7_5 = new import27.TemplateRef_(this._appEl_7,viewFactory_Dialog2);
    this._NgIf_7_6 = new import24.NgIf(this._appEl_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_9 = new import9.AppElement(9,3,this,this._anchor_9);
    this._TemplateRef_9_5 = new import27.TemplateRef_(this._appEl_9,viewFactory_Dialog3);
    this._NgIf_9_6 = new import24.NgIf(this._appEl_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_11 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','ui-dialog-content ui-widget-content');
    this._text_13 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this.renderer.projectNodes(this._el_12,import12.flattenNestedViewRenderNodes(this.projectableNodes[1]));
    this._text_14 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._text_15 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this.renderer.projectNodes(this._el_1,import12.flattenNestedViewRenderNodes(this.projectableNodes[2]));
    this._text_16 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._appEl_17 = new import9.AppElement(17,1,this,this._anchor_17);
    this._TemplateRef_17_5 = new import27.TemplateRef_(this._appEl_17,viewFactory_Dialog4);
    this._NgIf_17_6 = new import24.NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._expr_1 = import14.UNINITIALIZED;
    this._expr_2 = import14.UNINITIALIZED;
    this._expr_3 = import14.UNINITIALIZED;
    this._expr_4 = import14.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_1,'mousedown',this.eventHandler(this._handle_mousedown_1_0.bind(this)));
    this._map_0 = import12.pureProxy3((p0:any,p1:any,p2:any):{[key: string]:any} => {
      return {
        'ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow': p0,
        'ui-dialog-rtl': p1,
        'ui-dialog-draggable': p2
      }
      ;
    });
    this._expr_5 = import14.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_3,'mousedown',this.eventHandler(this._handle_mousedown_3_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_3,'mouseup',this.eventHandler(this._handle_mouseup_3_1.bind(this)));
    this._expr_8 = import14.UNINITIALIZED;
    this._expr_9 = import14.UNINITIALIZED;
    this._expr_10 = import14.UNINITIALIZED;
    this._expr_11 = import14.UNINITIALIZED;
    this._expr_12 = import14.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._text_19
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import24.NgIf) && (5 === requestNodeIndex))) { return this._NgIf_5_6; }
    if (((token === import27.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import24.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6; }
    if (((token === import27.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import24.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6; }
    if (((token === import27.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import24.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6; }
    if (((token === import23.NgClass) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._NgClass_1_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = (this.context.visible? 'visible': 'hidden');
    if (import12.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      var oldRenderVar:any = this._expr_4;
      if ((oldRenderVar == import14.UNINITIALIZED)) { (oldRenderVar = 'void'); }
      var newRenderVar:any = currVal_4;
      if ((newRenderVar == import14.UNINITIALIZED)) { (newRenderVar = 'void'); }
      this.componentType.animations['dialogState'](this,this._el_1,oldRenderVar,newRenderVar);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._map_0(true,this.context.rtl,this.context.draggable);
    if (import12.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgClass_1_3.ngClass = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (!throwOnChange) { this._NgClass_1_3.ngDoCheck(); }
    const currVal_8:any = this.context.header;
    if (import12.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgIf_5_6.ngIf = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this.context.headerFacet;
    if (import12.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgIf_7_6.ngIf = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this.context.closable;
    if (import12.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgIf_9_6.ngIf = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_12:any = this.context.resizable;
    if (import12.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgIf_17_6.ngIf = currVal_12;
      this._expr_12 = currVal_12;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = (this.context.visible? 'block': 'none');
    if (import12.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_1,'display',((this.viewUtils.sanitizer.sanitize(import28.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import28.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.width;
    if (import12.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementStyle(this._el_1,'width',((this.viewUtils.sanitizer.sanitize(import28.SecurityContext.STYLE,currVal_2) == (null as any))? (null as any): (this.viewUtils.sanitizer.sanitize(import28.SecurityContext.STYLE,currVal_2).toString() + 'px')));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.height;
    if (import12.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementStyle(this._el_1,'height',((this.viewUtils.sanitizer.sanitize(import28.SecurityContext.STYLE,currVal_3) == (null as any))? (null as any): (this.viewUtils.sanitizer.sanitize(import28.SecurityContext.STYLE,currVal_3).toString() + 'px')));
      this._expr_3 = currVal_3;
    }
    const currVal_11:any = this.context.contentHeight;
    if (import12.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementStyle(this._el_12,'height',((this.viewUtils.sanitizer.sanitize(import28.SecurityContext.STYLE,currVal_11) == (null as any))? (null as any): (this.viewUtils.sanitizer.sanitize(import28.SecurityContext.STYLE,currVal_11).toString() + 'px')));
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  detachInternal():void {
    this.componentType.animations['dialogState'](this,this._el_1,this._expr_4,'void');
  }
  private _handle_mousedown_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.moveOnTop()) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.initDrag($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_3_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.endDrag($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Dialog0(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<import1.Dialog> {
  if ((renderType_Dialog === (null as any))) { (renderType_Dialog = viewUtils.createRenderComponentType('c:/Users/eirwn/Documents/primeng-min/components/dialog/dialog.ts class Dialog - inline template',3,import16.ViewEncapsulation.None,styles_Dialog,{dialogState: Dialog_dialogState_factory})); }
  return new _View_Dialog0(viewUtils,parentInjector,declarationEl);
}
class _View_Dialog1 extends import8.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Dialog1,renderType_Dialog,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-dialog-title');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import12.interpolate(1,'',this.parent.context.header,'');
    if (import12.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Dialog1(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Dialog1(viewUtils,parentInjector,declarationEl);
}
class _View_Dialog2 extends import8.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Dialog2,renderType_Dialog,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-dialog-title');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this.renderer.projectNodes(this._el_0,import12.flattenNestedViewRenderNodes(this.projectableNodes[0]));
    this._text_2 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_Dialog2(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Dialog2(viewUtils,parentInjector,declarationEl);
}
class _View_Dialog3 extends import8.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import23.NgClass;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _map_0:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Dialog3,renderType_Dialog,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this.renderer.setElementAttribute(this._el_0,'href','#');
    this.renderer.setElementAttribute(this._el_0,'role','button');
    this._NgClass_0_3 = new import23.NgClass(this.parent.parentInjector.get(import25.IterableDiffers),this.parent.parentInjector.get(import26.KeyValueDiffers),new import15.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'span',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','fa fa-fw fa-close');
    this._text_3 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'mouseenter',this.eventHandler(this._handle_mouseenter_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'mouseleave',this.eventHandler(this._handle_mouseleave_0_2.bind(this)));
    this._map_0 = import12.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'ui-dialog-titlebar-icon ui-dialog-titlebar-close ui-corner-all': p0,
        'ui-state-hover': p1
      }
      ;
    });
    this._expr_3 = import14.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgClass_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = this._map_0(true,this.parent.context.hoverCloseIcon);
    if (import12.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgClass_0_3.ngClass = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (!throwOnChange) { this._NgClass_0_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.hide($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.hoverCloseIcon = true)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.hoverCloseIcon = false)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Dialog3(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Dialog3(viewUtils,parentInjector,declarationEl);
}
class _View_Dialog4 extends import8.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Dialog4,renderType_Dialog,import13.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import14.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se');
    this.renderer.setElementAttribute(this._el_0,'style','z-index: 90;');
    var disposable_0:Function = this.renderer.listen(this._el_0,'mousedown',this.eventHandler(this._handle_mousedown_0_0.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[disposable_0],[]);
    return (null as any);
  }
  private _handle_mousedown_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.initResize($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Dialog4(viewUtils:import12.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  return new _View_Dialog4(viewUtils,parentInjector,declarationEl);
}