/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../components/fileupload/fileupload';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '../../../components/common/shared';
import * as import4 from '../../../components/button/button';
import * as import5 from '../../../components/progressbar/progressbar';
import * as import6 from '../../../components/messages/messages';
import * as import7 from '@angular/common/src/localization';
import * as import8 from '@angular/core/src/di/injector';
import * as import9 from '@angular/core/src/i18n/tokens';
import * as import10 from '@angular/core/src/render/api';
import * as import11 from '@angular/core/src/linker/view';
import * as import12 from '@angular/core/src/linker/element';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from '@angular/core/src/linker/view_utils';
import * as import15 from '@angular/core/src/linker/view_type';
import * as import16 from '@angular/core/src/change_detection/change_detection';
import * as import17 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import18 from '@angular/core/src/metadata/view';
import * as import19 from '@angular/core/src/linker/component_factory';
import * as import20 from '@angular/common/src/directives/ng_class';
import * as import21 from '@angular/common/src/directives/ng_style';
import * as import22 from '../../../components/dom/domhandler';
import * as import23 from '@angular/common/src/directives/ng_if';
import * as import24 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import25 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from '@angular/core/src/linker/template_ref';
import * as import28 from '../messages/messages.ngfactory';
import * as import29 from '../common/shared.ngfactory';
import * as import30 from '../progressbar/progressbar.ngfactory';
import * as import31 from '@angular/common/src/directives/ng_for';
import * as import32 from '@angular/core/src/security';
class FileUploadModuleInjector extends import0.NgModuleInjector<import1.FileUploadModule> {
  _CommonModule_0:import2.CommonModule;
  _SharedModule_1:import3.SharedModule;
  _ButtonModule_2:import4.ButtonModule;
  _ProgressBarModule_3:import5.ProgressBarModule;
  _MessagesModule_4:import6.MessagesModule;
  _FileUploadModule_5:import1.FileUploadModule;
  __LOCALE_ID_6:any;
  __NgLocalization_7:import7.NgLocaleLocalization;
  __TRANSLATIONS_FORMAT_8:any;
  constructor(parent:import8.Injector) {
    super(parent,[],[]);
  }
  get _LOCALE_ID_6():any {
    if ((this.__LOCALE_ID_6 == (null as any))) { (this.__LOCALE_ID_6 = (null as any)); }
    return this.__LOCALE_ID_6;
  }
  get _NgLocalization_7():import7.NgLocaleLocalization {
    if ((this.__NgLocalization_7 == (null as any))) { (this.__NgLocalization_7 = new import7.NgLocaleLocalization(this._LOCALE_ID_6)); }
    return this.__NgLocalization_7;
  }
  get _TRANSLATIONS_FORMAT_8():any {
    if ((this.__TRANSLATIONS_FORMAT_8 == (null as any))) { (this.__TRANSLATIONS_FORMAT_8 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_8;
  }
  createInternal():import1.FileUploadModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._SharedModule_1 = new import3.SharedModule();
    this._ButtonModule_2 = new import4.ButtonModule();
    this._ProgressBarModule_3 = new import5.ProgressBarModule();
    this._MessagesModule_4 = new import6.MessagesModule();
    this._FileUploadModule_5 = new import1.FileUploadModule();
    return this._FileUploadModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.SharedModule)) { return this._SharedModule_1; }
    if ((token === import4.ButtonModule)) { return this._ButtonModule_2; }
    if ((token === import5.ProgressBarModule)) { return this._ProgressBarModule_3; }
    if ((token === import6.MessagesModule)) { return this._MessagesModule_4; }
    if ((token === import1.FileUploadModule)) { return this._FileUploadModule_5; }
    if ((token === import9.LOCALE_ID)) { return this._LOCALE_ID_6; }
    if ((token === import7.NgLocalization)) { return this._NgLocalization_7; }
    if ((token === import9.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_8; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const FileUploadModuleNgFactory:import0.NgModuleFactory<import1.FileUploadModule> = new import0.NgModuleFactory(FileUploadModuleInjector,import1.FileUploadModule);
var renderType_FileUpload_Host:import10.RenderComponentType = (null as any);
class _View_FileUpload_Host0 extends import11.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import12.AppElement;
  _FileUpload_0_4:import1.FileUpload;
  _query_PrimeTemplate_0_0:import13.QueryList<any>;
  constructor(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement) {
    super(_View_FileUpload_Host0,renderType_FileUpload_Host,import15.ViewType.HOST,viewUtils,parentInjector,declarationEl,import16.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.AppElement {
    this._el_0 = this.selectOrCreateHostElement('p-fileUpload',rootSelector,(null as any));
    this._appEl_0 = new import12.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FileUpload0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FileUpload_0_4 = new import1.FileUpload(this.parentInjector.get(import17.DomSanitizer));
    this._query_PrimeTemplate_0_0 = new import13.QueryList<any>();
    this._appEl_0.initComponent(this._FileUpload_0_4,[],compView_0);
    compView_0.create(this._FileUpload_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.FileUpload) && (0 === requestNodeIndex))) { return this._FileUpload_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._FileUpload_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_PrimeTemplate_0_0.dirty) {
        this._query_PrimeTemplate_0_0.reset([]);
        this._FileUpload_0_4.templates = this._query_PrimeTemplate_0_0;
        this._query_PrimeTemplate_0_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._FileUpload_0_4.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_FileUpload_Host0(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement):import11.AppView<any> {
  if ((renderType_FileUpload_Host === (null as any))) { (renderType_FileUpload_Host = viewUtils.createRenderComponentType('',0,import18.ViewEncapsulation.None,[],{})); }
  return new _View_FileUpload_Host0(viewUtils,parentInjector,declarationEl);
}
export const FileUploadNgFactory:import19.ComponentFactory<import1.FileUpload> = new import19.ComponentFactory<import1.FileUpload>('p-fileUpload',viewFactory_FileUpload_Host0,import1.FileUpload);
const styles_FileUpload:any[] = [];
var renderType_FileUpload:import10.RenderComponentType = (null as any);
class _View_FileUpload0 extends import11.AppView<import1.FileUpload> {
  _text_0:any;
  _el_1:any;
  _NgClass_1_3:import20.NgClass;
  _NgStyle_1_4:import21.NgStyle;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _DomHandler_5_3:import22.DomHandler;
  _Button_5_4:import4.Button;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _DomHandler_10_3:import22.DomHandler;
  _Button_10_4:import4.Button;
  _text_11:any;
  _el_12:any;
  _DomHandler_12_3:import22.DomHandler;
  _Button_12_4:import4.Button;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _NgClass_15_3:import20.NgClass;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import12.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import23.NgIf;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import12.AppElement;
  _Messages_19_4:import6.Messages;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import12.AppElement;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import23.NgIf;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import12.AppElement;
  _TemplateLoader_23_5:import3.TemplateLoader;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  _map_0:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  constructor(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement) {
    super(_View_FileUpload0,renderType_FileUpload,import15.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import16.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._NgClass_1_3 = new import20.NgClass(this.parentInjector.get(import24.IterableDiffers),this.parentInjector.get(import25.KeyValueDiffers),new import26.ElementRef(this._el_1),this.renderer);
    this._NgStyle_1_4 = new import21.NgStyle(this.parentInjector.get(import25.KeyValueDiffers),new import26.ElementRef(this._el_1),this.renderer);
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','ui-fileupload-buttonbar ui-widget-header ui-corner-top');
    this._text_4 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','ui-fileupload-choose');
    this.renderer.setElementAttribute(this._el_5,'icon','fa-plus');
    this.renderer.setElementAttribute(this._el_5,'label','Choose');
    this.renderer.setElementAttribute(this._el_5,'pButton','');
    this.renderer.setElementAttribute(this._el_5,'type','button');
    this._DomHandler_5_3 = new import22.DomHandler();
    this._Button_5_4 = new import4.Button(new import26.ElementRef(this._el_5),this._DomHandler_5_3);
    this._text_6 = this.renderer.createText(this._el_5,' \n                    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'input',(null as any));
    this.renderer.setElementAttribute(this._el_7,'type','file');
    this._text_8 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._text_9 = this.renderer.createText(this._el_3,'\n\n                ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_3,'button',(null as any));
    this.renderer.setElementAttribute(this._el_10,'icon','fa-upload');
    this.renderer.setElementAttribute(this._el_10,'label','Upload');
    this.renderer.setElementAttribute(this._el_10,'pButton','');
    this.renderer.setElementAttribute(this._el_10,'type','button');
    this._DomHandler_10_3 = new import22.DomHandler();
    this._Button_10_4 = new import4.Button(new import26.ElementRef(this._el_10),this._DomHandler_10_3);
    this._text_11 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_3,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'icon','fa-close');
    this.renderer.setElementAttribute(this._el_12,'label','Cancel');
    this.renderer.setElementAttribute(this._el_12,'pButton','');
    this.renderer.setElementAttribute(this._el_12,'type','button');
    this._DomHandler_12_3 = new import22.DomHandler();
    this._Button_12_4 = new import4.Button(new import26.ElementRef(this._el_12),this._DomHandler_12_3);
    this._text_13 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_14 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_1,'div',(null as any));
    this._NgClass_15_3 = new import20.NgClass(this.parentInjector.get(import24.IterableDiffers),this.parentInjector.get(import25.KeyValueDiffers),new import26.ElementRef(this._el_15),this.renderer);
    this._text_16 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_17 = new import12.AppElement(17,15,this,this._anchor_17);
    this._TemplateRef_17_5 = new import27.TemplateRef_(this._appEl_17,viewFactory_FileUpload1);
    this._NgIf_17_6 = new import23.NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_15,'\n                \n                ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_15,'p-messages',(null as any));
    this._appEl_19 = new import12.AppElement(19,15,this,this._el_19);
    var compView_19:any = import28.viewFactory_Messages0(this.viewUtils,this.injector(19),this._appEl_19);
    this._Messages_19_4 = new import6.Messages();
    this._appEl_19.initComponent(this._Messages_19_4,[],compView_19);
    compView_19.create(this._Messages_19_4,[],(null as any));
    this._text_20 = this.renderer.createText(this._el_15,'\n                \n                ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_21 = new import12.AppElement(21,15,this,this._anchor_21);
    this._TemplateRef_21_5 = new import27.TemplateRef_(this._appEl_21,viewFactory_FileUpload2);
    this._NgIf_21_6 = new import23.NgIf(this._appEl_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText(this._el_15,'\n                \n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_15,'p-templateLoader',(null as any));
    this._appEl_23 = new import12.AppElement(23,15,this,this._el_23);
    var compView_23:any = import29.viewFactory_TemplateLoader0(this.viewUtils,this.injector(23),this._appEl_23);
    this._TemplateLoader_23_5 = new import3.TemplateLoader(this._appEl_23.vcRef);
    this._appEl_23.initComponent(this._TemplateLoader_23_5,[],compView_23);
    compView_23.create(this._TemplateLoader_23_5,[],(null as any));
    this._text_24 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._text_25 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._expr_0 = import16.UNINITIALIZED;
    this._expr_1 = import16.UNINITIALIZED;
    this._expr_2 = import16.UNINITIALIZED;
    this._expr_10 = import16.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'mouseenter',this.eventHandler(this._handle_mouseenter_5_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_5,'mouseleave',this.eventHandler(this._handle_mouseleave_5_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_5,'mousedown',this.eventHandler(this._handle_mousedown_5_3.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_5,'mouseup',this.eventHandler(this._handle_mouseup_5_4.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_5,'focus',this.eventHandler(this._handle_focus_5_5.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_5,'blur',this.eventHandler(this._handle_blur_5_6.bind(this)));
    this._expr_11 = import16.UNINITIALIZED;
    this._expr_12 = import16.UNINITIALIZED;
    this._expr_13 = import16.UNINITIALIZED;
    this._expr_14 = import16.UNINITIALIZED;
    this._expr_15 = import16.UNINITIALIZED;
    this._expr_16 = import16.UNINITIALIZED;
    this._expr_18 = import16.UNINITIALIZED;
    this._expr_19 = import16.UNINITIALIZED;
    this._expr_20 = import16.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_7,'change',this.eventHandler(this._handle_change_7_0.bind(this)));
    this._expr_28 = import16.UNINITIALIZED;
    var disposable_8:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_10,'mouseenter',this.eventHandler(this._handle_mouseenter_10_1.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_10,'mouseleave',this.eventHandler(this._handle_mouseleave_10_2.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_10,'mousedown',this.eventHandler(this._handle_mousedown_10_3.bind(this)));
    var disposable_12:Function = this.renderer.listen(this._el_10,'mouseup',this.eventHandler(this._handle_mouseup_10_4.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_10,'focus',this.eventHandler(this._handle_focus_10_5.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_10,'blur',this.eventHandler(this._handle_blur_10_6.bind(this)));
    this._expr_29 = import16.UNINITIALIZED;
    this._expr_30 = import16.UNINITIALIZED;
    this._expr_31 = import16.UNINITIALIZED;
    this._expr_32 = import16.UNINITIALIZED;
    this._expr_33 = import16.UNINITIALIZED;
    this._expr_34 = import16.UNINITIALIZED;
    this._expr_42 = import16.UNINITIALIZED;
    var disposable_15:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    var disposable_16:Function = this.renderer.listen(this._el_12,'mouseenter',this.eventHandler(this._handle_mouseenter_12_1.bind(this)));
    var disposable_17:Function = this.renderer.listen(this._el_12,'mouseleave',this.eventHandler(this._handle_mouseleave_12_2.bind(this)));
    var disposable_18:Function = this.renderer.listen(this._el_12,'mousedown',this.eventHandler(this._handle_mousedown_12_3.bind(this)));
    var disposable_19:Function = this.renderer.listen(this._el_12,'mouseup',this.eventHandler(this._handle_mouseup_12_4.bind(this)));
    var disposable_20:Function = this.renderer.listen(this._el_12,'focus',this.eventHandler(this._handle_focus_12_5.bind(this)));
    var disposable_21:Function = this.renderer.listen(this._el_12,'blur',this.eventHandler(this._handle_blur_12_6.bind(this)));
    this._expr_43 = import16.UNINITIALIZED;
    this._expr_44 = import16.UNINITIALIZED;
    this._expr_45 = import16.UNINITIALIZED;
    this._expr_46 = import16.UNINITIALIZED;
    this._expr_47 = import16.UNINITIALIZED;
    this._expr_48 = import16.UNINITIALIZED;
    var disposable_22:Function = this.renderer.listen(this._el_15,'dragenter',this.eventHandler(this._handle_dragenter_15_0.bind(this)));
    var disposable_23:Function = this.renderer.listen(this._el_15,'dragover',this.eventHandler(this._handle_dragover_15_1.bind(this)));
    var disposable_24:Function = this.renderer.listen(this._el_15,'dragleave',this.eventHandler(this._handle_dragleave_15_2.bind(this)));
    var disposable_25:Function = this.renderer.listen(this._el_15,'drop',this.eventHandler(this._handle_drop_15_3.bind(this)));
    this._map_0 = import14.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'ui-fileupload-content ui-widget-content ui-corner-bottom': p0,
        'ui-fileupload-highlight': p1
      }
      ;
    });
    this._expr_53 = import16.UNINITIALIZED;
    this._expr_54 = import16.UNINITIALIZED;
    this._expr_55 = import16.UNINITIALIZED;
    this._expr_56 = import16.UNINITIALIZED;
    this._expr_57 = import16.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15,
      disposable_16,
      disposable_17,
      disposable_18,
      disposable_19,
      disposable_20,
      disposable_21,
      disposable_22,
      disposable_23,
      disposable_24,
      disposable_25
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.DomHandler) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._DomHandler_5_3; }
    if (((token === import4.Button) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_5_4; }
    if (((token === import22.DomHandler) && (10 === requestNodeIndex))) { return this._DomHandler_10_3; }
    if (((token === import4.Button) && (10 === requestNodeIndex))) { return this._Button_10_4; }
    if (((token === import22.DomHandler) && (12 === requestNodeIndex))) { return this._DomHandler_12_3; }
    if (((token === import4.Button) && (12 === requestNodeIndex))) { return this._Button_12_4; }
    if (((token === import27.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import23.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6; }
    if (((token === import6.Messages) && (19 === requestNodeIndex))) { return this._Messages_19_4; }
    if (((token === import27.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import23.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6; }
    if (((token === import3.TemplateLoader) && (23 === requestNodeIndex))) { return this._TemplateLoader_23_5; }
    if (((token === import20.NgClass) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._NgClass_15_3; }
    if (((token === import20.NgClass) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._NgClass_1_3; }
    if (((token === import21.NgStyle) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._NgStyle_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.styleClass;
    if (import14.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgClass_1_3.klass = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'ui-fileupload ui-widget';
    if (import14.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_1_3.ngClass = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgClass_1_3.ngDoCheck(); }
    const currVal_2:any = this.context.style;
    if (import14.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgStyle_1_4.ngStyle = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgStyle_1_4.ngDoCheck(); }
    const currVal_11:any = 'fa-plus';
    if (import14.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Button_5_4.icon = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = 'Choose';
    if (import14.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Button_5_4.label = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_29:any = 'fa-upload';
    if (import14.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this._Button_10_4.icon = currVal_29;
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = 'Upload';
    if (import14.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._Button_10_4.label = currVal_30;
      this._expr_30 = currVal_30;
    }
    const currVal_43:any = 'fa-close';
    if (import14.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this._Button_12_4.icon = currVal_43;
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = 'Cancel';
    if (import14.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this._Button_12_4.label = currVal_44;
      this._expr_44 = currVal_44;
    }
    const currVal_53:any = this._map_0(true,this.context.dragHighlight);
    if (import14.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this._NgClass_15_3.ngClass = currVal_53;
      this._expr_53 = currVal_53;
    }
    if (!throwOnChange) { this._NgClass_15_3.ngDoCheck(); }
    const currVal_54:any = this.context.hasFiles();
    if (import14.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this._NgIf_17_6.ngIf = currVal_54;
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = this.context.msgs;
    if (import14.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this._Messages_19_4.value = currVal_55;
      this._expr_55 = currVal_55;
    }
    const currVal_56:any = this.context.hasFiles();
    if (import14.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this._NgIf_21_6.ngIf = currVal_56;
      this._expr_56 = currVal_56;
    }
    const currVal_57:any = this.context.contentTemplate;
    if (import14.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this._TemplateLoader_23_5.template = currVal_57;
      this._expr_57 = currVal_57;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TemplateLoader_23_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_10:any = this.context.disabled;
    if (import14.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_5,'disabled',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_13:any = (this._Button_5_4.hover && !this._Button_5_4.isDisabled());
    if (import14.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_5,'ui-state-hover',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._Button_5_4.focus;
    if (import14.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_5,'ui-state-focus',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._Button_5_4.active;
    if (import14.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_5,'ui-state-active',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._Button_5_4.isDisabled();
    if (import14.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_5,'ui-state-disabled',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = this.context.multiple;
    if (import14.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementProperty(this._el_7,'multiple',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this.context.accept;
    if (import14.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementProperty(this._el_7,'accept',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this.context.disabled;
    if (import14.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementProperty(this._el_7,'disabled',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_28:boolean = !this.context.hasFiles();
    if (import14.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementProperty(this._el_10,'disabled',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_31:any = (this._Button_10_4.hover && !this._Button_10_4.isDisabled());
    if (import14.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_10,'ui-state-hover',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._Button_10_4.focus;
    if (import14.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_10,'ui-state-focus',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._Button_10_4.active;
    if (import14.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_10,'ui-state-active',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._Button_10_4.isDisabled();
    if (import14.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_10,'ui-state-disabled',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_42:boolean = !this.context.hasFiles();
    if (import14.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementProperty(this._el_12,'disabled',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_45:any = (this._Button_12_4.hover && !this._Button_12_4.isDisabled());
    if (import14.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_12,'ui-state-hover',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._Button_12_4.focus;
    if (import14.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_12,'ui-state-focus',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._Button_12_4.active;
    if (import14.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_12,'ui-state-active',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._Button_12_4.isDisabled();
    if (import14.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_12,'ui-state-disabled',currVal_48);
      this._expr_48 = currVal_48;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_5_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_10_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_12_4.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Button_5_4.ngOnDestroy();
    this._Button_10_4.ngOnDestroy();
    this._Button_12_4.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onChooseClick($event,this._el_7)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_5_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_5_4.onMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_5_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_5_4.onMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_5_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_5_4.onMouseDown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_5_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_5_4.onMouseUp($event)) !== false);
    return (true && pd_0);
  }
  private _handle_focus_5_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_5_4.onFocus($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_5_6($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_5_4.onBlur($event)) !== false);
    return (true && pd_0);
  }
  private _handle_change_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onFileSelect($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.upload()) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_10_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_10_4.onMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_10_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_10_4.onMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_10_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_10_4.onMouseDown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_10_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_10_4.onMouseUp($event)) !== false);
    return (true && pd_0);
  }
  private _handle_focus_10_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_10_4.onFocus($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_10_6($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_10_4.onBlur($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.clear()) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_12_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_12_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_12_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onMouseDown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_12_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onMouseUp($event)) !== false);
    return (true && pd_0);
  }
  private _handle_focus_12_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onFocus($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_12_6($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onBlur($event)) !== false);
    return (true && pd_0);
  }
  private _handle_dragenter_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onDragEnter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_dragover_15_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onDragOver($event)) !== false);
    return (true && pd_0);
  }
  private _handle_dragleave_15_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onDragLeave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_drop_15_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onDrop($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_FileUpload0(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement):import11.AppView<import1.FileUpload> {
  if ((renderType_FileUpload === (null as any))) { (renderType_FileUpload = viewUtils.createRenderComponentType('c:/Users/eirwn/Documents/primeng-min/components/fileupload/fileupload.ts class FileUpload - inline template',0,import18.ViewEncapsulation.None,styles_FileUpload,{})); }
  return new _View_FileUpload0(viewUtils,parentInjector,declarationEl);
}
class _View_FileUpload1 extends import11.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import12.AppElement;
  _ProgressBar_0_4:import5.ProgressBar;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement) {
    super(_View_FileUpload1,renderType_FileUpload,import15.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import16.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p-progressBar',(null as any));
    this._appEl_0 = new import12.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import30.viewFactory_ProgressBar0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ProgressBar_0_4 = new import5.ProgressBar();
    this._appEl_0.initComponent(this._ProgressBar_0_4,[],compView_0);
    compView_0.create(this._ProgressBar_0_4,[],(null as any));
    this._expr_0 = import16.UNINITIALIZED;
    this._expr_1 = import16.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.ProgressBar) && (0 === requestNodeIndex))) { return this._ProgressBar_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.context.progress;
    if (import14.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._ProgressBar_0_4.value = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = false;
    if (import14.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ProgressBar_0_4.showValue = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_FileUpload1(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement):import11.AppView<any> {
  return new _View_FileUpload1(viewUtils,parentInjector,declarationEl);
}
class _View_FileUpload2 extends import11.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import12.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import23.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import12.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import23.NgIf;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement) {
    super(_View_FileUpload2,renderType_FileUpload,import15.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import16.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-fileupload-files');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import12.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import27.TemplateRef_(this._appEl_2,viewFactory_FileUpload3);
    this._NgIf_2_6 = new import23.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import12.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import27.TemplateRef_(this._appEl_4,viewFactory_FileUpload6);
    this._NgIf_4_6 = new import23.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_0 = import16.UNINITIALIZED;
    this._expr_1 = import16.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import23.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import27.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import23.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:boolean = !this.parent.context.fileTemplate;
    if (import14.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.fileTemplate;
    if (import14.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_FileUpload2(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement):import11.AppView<any> {
  return new _View_FileUpload2(viewUtils,parentInjector,declarationEl);
}
class _View_FileUpload3 extends import11.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import12.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import31.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement) {
    super(_View_FileUpload3,renderType_FileUpload,import15.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import16.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import12.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import27.TemplateRef_(this._appEl_2,viewFactory_FileUpload4);
    this._NgFor_2_6 = new import31.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parent.parentInjector.get(import24.IterableDiffers),this.parent.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._expr_0 = import16.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import31.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import16.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.parent.context.files;
    if (import14.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import16.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_FileUpload3(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement):import11.AppView<any> {
  return new _View_FileUpload3(viewUtils,parentInjector,declarationEl);
}
class _View_FileUpload4 extends import11.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import12.AppElement;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import23.NgIf;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _DomHandler_12_3:import22.DomHandler;
  _Button_12_4:import4.Button;
  _text_13:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement) {
    super(_View_FileUpload4,renderType_FileUpload,import15.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import16.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-fileupload-row');
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_3 = new import12.AppElement(3,2,this,this._anchor_3);
    this._TemplateRef_3_5 = new import27.TemplateRef_(this._appEl_3,viewFactory_FileUpload5);
    this._NgIf_3_6 = new import23.NgIf(this._appEl_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'div',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_0,'div',(null as any));
    this._el_12 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'icon','fa-close');
    this.renderer.setElementAttribute(this._el_12,'pButton','');
    this.renderer.setElementAttribute(this._el_12,'type','button');
    this._DomHandler_12_3 = new import22.DomHandler();
    this._Button_12_4 = new import4.Button(new import26.ElementRef(this._el_12),this._DomHandler_12_3);
    this._text_13 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._expr_0 = import16.UNINITIALIZED;
    this._expr_1 = import16.UNINITIALIZED;
    this._expr_2 = import16.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'mouseenter',this.eventHandler(this._handle_mouseenter_12_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'mouseleave',this.eventHandler(this._handle_mouseleave_12_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_12,'mousedown',this.eventHandler(this._handle_mousedown_12_3.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_12,'mouseup',this.eventHandler(this._handle_mouseup_12_4.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_12,'focus',this.eventHandler(this._handle_focus_12_5.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_12,'blur',this.eventHandler(this._handle_blur_12_6.bind(this)));
    this._expr_10 = import16.UNINITIALIZED;
    this._expr_11 = import16.UNINITIALIZED;
    this._expr_12 = import16.UNINITIALIZED;
    this._expr_13 = import16.UNINITIALIZED;
    this._expr_14 = import16.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._anchor_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import23.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6; }
    if (((token === import22.DomHandler) && (12 === requestNodeIndex))) { return this._DomHandler_12_3; }
    if (((token === import4.Button) && (12 === requestNodeIndex))) { return this._Button_12_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.parent.parent.context.isImage(this.context.$implicit);
    if (import14.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_3_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_10:any = 'fa-close';
    if (import14.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Button_12_4.icon = currVal_10;
      this._expr_10 = currVal_10;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import14.interpolate(1,'',this.context.$implicit.name,'');
    if (import14.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import14.interpolate(1,'',this.parent.parent.parent.context.formatSize(this.context.$implicit.size),'');
    if (import14.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_9,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_11:any = (this._Button_12_4.hover && !this._Button_12_4.isDisabled());
    if (import14.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_12,'ui-state-hover',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._Button_12_4.focus;
    if (import14.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_12,'ui-state-focus',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._Button_12_4.active;
    if (import14.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_12,'ui-state-active',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._Button_12_4.isDisabled();
    if (import14.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_12,'ui-state-disabled',currVal_14);
      this._expr_14 = currVal_14;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_12_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Button_12_4.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.remove(this.parent.parent.parent.context.i)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_12_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_12_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_12_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onMouseDown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_12_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onMouseUp($event)) !== false);
    return (true && pd_0);
  }
  private _handle_focus_12_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onFocus($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_12_6($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Button_12_4.onBlur($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_FileUpload4(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement):import11.AppView<any> {
  return new _View_FileUpload4(viewUtils,parentInjector,declarationEl);
}
class _View_FileUpload5 extends import11.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement) {
    super(_View_FileUpload5,renderType_FileUpload,import15.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import16.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_0 = import16.UNINITIALIZED;
    this._expr_1 = import16.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.$implicit.objectURL;
    if (import14.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import32.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.parent.parent.parent.context.previewWidth;
    if (import14.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'width',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_FileUpload5(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement):import11.AppView<any> {
  return new _View_FileUpload5(viewUtils,parentInjector,declarationEl);
}
class _View_FileUpload6 extends import11.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import12.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import31.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement) {
    super(_View_FileUpload6,renderType_FileUpload,import15.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import16.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import12.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import27.TemplateRef_(this._appEl_2,viewFactory_FileUpload7);
    this._NgFor_2_6 = new import31.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parent.parentInjector.get(import24.IterableDiffers),this.parent.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._expr_0 = import16.UNINITIALIZED;
    this._expr_1 = import16.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import31.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import16.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.parent.context.files;
    if (import14.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import16.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.parent.context.fileTemplate;
    if (import14.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_2_6.ngForTemplate = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForTemplate'] = new import16.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_FileUpload6(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement):import11.AppView<any> {
  return new _View_FileUpload6(viewUtils,parentInjector,declarationEl);
}
class _View_FileUpload7 extends import11.AppView<any> {
  constructor(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement) {
    super(_View_FileUpload7,renderType_FileUpload,import15.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import16.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import12.AppElement {
    this.init([],[],[],[]);
    return (null as any);
  }
}
function viewFactory_FileUpload7(viewUtils:import14.ViewUtils,parentInjector:import8.Injector,declarationEl:import12.AppElement):import11.AppView<any> {
  return new _View_FileUpload7(viewUtils,parentInjector,declarationEl);
}