/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../components/megamenu/megamenu';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/common/src/localization';
import * as import4 from '@angular/core/src/di/injector';
import * as import5 from '@angular/core/src/i18n/tokens';
import * as import6 from '@angular/core/src/render/api';
import * as import7 from '@angular/core/src/linker/view';
import * as import8 from '@angular/core/src/linker/element';
import * as import9 from '../../../components/dom/domhandler';
import * as import10 from '@angular/core/src/linker/view_utils';
import * as import11 from '@angular/core/src/linker/view_type';
import * as import12 from '@angular/core/src/change_detection/change_detection';
import * as import13 from '@angular/core/src/linker/element_ref';
import * as import14 from '@angular/router/src/router';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from '@angular/common/src/directives/ng_class';
import * as import18 from '@angular/common/src/directives/ng_style';
import * as import19 from '@angular/common/src/directives/ng_for';
import * as import20 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import21 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/common/src/directives/ng_if';
import * as import24 from '@angular/core/src/security';
class MegaMenuModuleInjector extends import0.NgModuleInjector<import1.MegaMenuModule> {
  _CommonModule_0:import2.CommonModule;
  _MegaMenuModule_1:import1.MegaMenuModule;
  __LOCALE_ID_2:any;
  __NgLocalization_3:import3.NgLocaleLocalization;
  __TRANSLATIONS_FORMAT_4:any;
  constructor(parent:import4.Injector) {
    super(parent,[],[]);
  }
  get _LOCALE_ID_2():any {
    if ((this.__LOCALE_ID_2 == (null as any))) { (this.__LOCALE_ID_2 = (null as any)); }
    return this.__LOCALE_ID_2;
  }
  get _NgLocalization_3():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == (null as any))) { (this.__NgLocalization_3 = new import3.NgLocaleLocalization(this._LOCALE_ID_2)); }
    return this.__NgLocalization_3;
  }
  get _TRANSLATIONS_FORMAT_4():any {
    if ((this.__TRANSLATIONS_FORMAT_4 == (null as any))) { (this.__TRANSLATIONS_FORMAT_4 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_4;
  }
  createInternal():import1.MegaMenuModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._MegaMenuModule_1 = new import1.MegaMenuModule();
    return this._MegaMenuModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.MegaMenuModule)) { return this._MegaMenuModule_1; }
    if ((token === import5.LOCALE_ID)) { return this._LOCALE_ID_2; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_3; }
    if ((token === import5.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_4; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MegaMenuModuleNgFactory:import0.NgModuleFactory<import1.MegaMenuModule> = new import0.NgModuleFactory(MegaMenuModuleInjector,import1.MegaMenuModule);
var renderType_MegaMenu_Host:import6.RenderComponentType = (null as any);
class _View_MegaMenu_Host0 extends import7.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import8.AppElement;
  _DomHandler_0_4:import9.DomHandler;
  _MegaMenu_0_5:import1.MegaMenu;
  constructor(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement) {
    super(_View_MegaMenu_Host0,renderType_MegaMenu_Host,import11.ViewType.HOST,viewUtils,parentInjector,declarationEl,import12.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.AppElement {
    this._el_0 = this.selectOrCreateHostElement('p-megaMenu',rootSelector,(null as any));
    this._appEl_0 = new import8.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MegaMenu0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DomHandler_0_4 = new import9.DomHandler();
    this._MegaMenu_0_5 = new import1.MegaMenu(new import13.ElementRef(this._el_0),this._DomHandler_0_4,this.renderer,this.parentInjector.get(import14.Router));
    this._appEl_0.initComponent(this._MegaMenu_0_5,[],compView_0);
    compView_0.create(this._MegaMenu_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.DomHandler) && (0 === requestNodeIndex))) { return this._DomHandler_0_4; }
    if (((token === import1.MegaMenu) && (0 === requestNodeIndex))) { return this._MegaMenu_0_5; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._MegaMenu_0_5.ngOnDestroy();
  }
}
function viewFactory_MegaMenu_Host0(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement):import7.AppView<any> {
  if ((renderType_MegaMenu_Host === (null as any))) { (renderType_MegaMenu_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,[],{})); }
  return new _View_MegaMenu_Host0(viewUtils,parentInjector,declarationEl);
}
export const MegaMenuNgFactory:import16.ComponentFactory<import1.MegaMenu> = new import16.ComponentFactory<import1.MegaMenu>('p-megaMenu',viewFactory_MegaMenu_Host0,import1.MegaMenu);
const styles_MegaMenu:any[] = [];
var renderType_MegaMenu:import6.RenderComponentType = (null as any);
class _View_MegaMenu0 extends import7.AppView<import1.MegaMenu> {
  _text_0:any;
  _el_1:any;
  _NgClass_1_3:import17.NgClass;
  _NgStyle_1_4:import18.NgStyle;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _appEl_5:import8.AppElement;
  _TemplateRef_5_5:any;
  _NgFor_5_6:import19.NgFor;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_0:any;
  _map_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement) {
    super(_View_MegaMenu0,renderType_MegaMenu,import11.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import12.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._NgClass_1_3 = new import17.NgClass(this.parentInjector.get(import20.IterableDiffers),this.parentInjector.get(import21.KeyValueDiffers),new import13.ElementRef(this._el_1),this.renderer);
    this._NgStyle_1_4 = new import18.NgStyle(this.parentInjector.get(import21.KeyValueDiffers),new import13.ElementRef(this._el_1),this.renderer);
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','ui-menu-list ui-helper-reset');
    this._text_4 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_5 = new import8.AppElement(5,3,this,this._anchor_5);
    this._TemplateRef_5_5 = new import22.TemplateRef_(this._appEl_5,viewFactory_MegaMenu1);
    this._NgFor_5_6 = new import19.NgFor(this._appEl_5.vcRef,this._TemplateRef_5_5,this.parentInjector.get(import20.IterableDiffers),this.ref);
    this._text_6 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_7 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._expr_0 = import12.UNINITIALIZED;
    this._map_0 = import10.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'ui-menu ui-menubar ui-megamenu ui-widget ui-widget-content ui-corner-all ui-helper-clearfix': p0,
        'ui-megamenu-vertical': p1
      }
      ;
    });
    this._expr_1 = import12.UNINITIALIZED;
    this._expr_2 = import12.UNINITIALIZED;
    this._expr_3 = import12.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._text_7,
      this._text_8
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import19.NgFor) && (5 === requestNodeIndex))) { return this._NgFor_5_6; }
    if (((token === import17.NgClass) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NgClass_1_3; }
    if (((token === import18.NgStyle) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NgStyle_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import12.SimpleChange} = (null as any);
    const currVal_0:any = this.context.styleClass;
    if (import10.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgClass_1_3.klass = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._map_0(true,(this.context.orientation == 'vertical'));
    if (import10.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_1_3.ngClass = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgClass_1_3.ngDoCheck(); }
    const currVal_2:any = this.context.style;
    if (import10.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgStyle_1_4.ngStyle = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgStyle_1_4.ngDoCheck(); }
    changes = (null as any);
    const currVal_3:any = this.context.model;
    if (import10.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgFor_5_6.ngForOf = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import12.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgFor_5_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_5_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_MegaMenu0(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement):import7.AppView<import1.MegaMenu> {
  if ((renderType_MegaMenu === (null as any))) { (renderType_MegaMenu = viewUtils.createRenderComponentType('c:/Users/eirwn/Documents/primeng-min/components/megamenu/megamenu.ts class MegaMenu - inline template',0,import15.ViewEncapsulation.None,styles_MegaMenu,{})); }
  return new _View_MegaMenu0(viewUtils,parentInjector,declarationEl);
}
class _View_MegaMenu1 extends import7.AppView<any> {
  _text_0:any;
  _el_1:any;
  _NgClass_1_3:import17.NgClass;
  _text_2:any;
  _el_3:any;
  _NgClass_3_3:import17.NgClass;
  _text_4:any;
  _el_5:any;
  _NgClass_5_3:import17.NgClass;
  _text_6:any;
  _el_7:any;
  _NgClass_7_3:import17.NgClass;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import8.AppElement;
  _TemplateRef_16_5:any;
  _NgFor_16_6:import19.NgFor;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _map_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  _map_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  _map_2:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement) {
    super(_View_MegaMenu1,renderType_MegaMenu,import11.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import12.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'li',(null as any));
    this._NgClass_1_3 = new import17.NgClass(this.parent.parentInjector.get(import20.IterableDiffers),this.parent.parentInjector.get(import21.KeyValueDiffers),new import13.ElementRef(this._el_1),this.renderer);
    this._text_2 = this.renderer.createText(this._el_1,'\n                        ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'a',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','ui-menuitem-link ui-corner-all ui-submenu-link');
    this._NgClass_3_3 = new import17.NgClass(this.parent.parentInjector.get(import20.IterableDiffers),this.parent.parentInjector.get(import21.KeyValueDiffers),new import13.ElementRef(this._el_3),this.renderer);
    this._text_4 = this.renderer.createText(this._el_3,'\n                            ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'span',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','ui-submenu-icon fa fa-fw');
    this._NgClass_5_3 = new import17.NgClass(this.parent.parentInjector.get(import20.IterableDiffers),this.parent.parentInjector.get(import21.KeyValueDiffers),new import13.ElementRef(this._el_5),this.renderer);
    this._text_6 = this.renderer.createText(this._el_3,'\n                            ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_3,'span',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','ui-menuitem-icon fa fa-fw');
    this._NgClass_7_3 = new import17.NgClass(this.parent.parentInjector.get(import20.IterableDiffers),this.parent.parentInjector.get(import21.KeyValueDiffers),new import13.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText(this._el_3,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_1,'\n                        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','ui-megamenu-panel ui-widget-content ui-menu-list ui-corner-all ui-helper-clearfix ui-menu-child ui-shadow');
    this._text_11 = this.renderer.createText(this._el_10,'\n                            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','ui-grid');
    this._text_13 = this.renderer.createText(this._el_12,'\n                                ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','ui-grid-row');
    this._text_15 = this.renderer.createText(this._el_14,'\n                                    ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._appEl_16 = new import8.AppElement(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import22.TemplateRef_(this._appEl_16,viewFactory_MegaMenu2);
    this._NgFor_16_6 = new import19.NgFor(this._appEl_16.vcRef,this._TemplateRef_16_5,this.parent.parentInjector.get(import20.IterableDiffers),this.parent.ref);
    this._text_17 = this.renderer.createText(this._el_14,'\n                                ',(null as any));
    this._text_18 = this.renderer.createText(this._el_12,'\n                            ',(null as any));
    this._text_19 = this.renderer.createText(this._el_10,'\n                        ',(null as any));
    this._text_20 = this.renderer.createText(this._el_1,'\n                    ',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n                ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'mouseenter',this.eventHandler(this._handle_mouseenter_1_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_1,'mouseleave',this.eventHandler(this._handle_mouseleave_1_1.bind(this)));
    this._map_0 = import10.pureProxy3((p0:any,p1:any,p2:any):{[key: string]:any} => {
      return {
        'ui-menuitem ui-widget ui-corner-all': p0,
        'ui-menu-parent': p1,
        'ui-menuitem-active': p2
      }
      ;
    });
    this._expr_2 = import12.UNINITIALIZED;
    this._expr_3 = import12.UNINITIALIZED;
    this._map_1 = import10.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'ui-state-hover': p0,
        'ui-state-disabled': p1
      }
      ;
    });
    this._expr_4 = import12.UNINITIALIZED;
    this._expr_5 = import12.UNINITIALIZED;
    this._map_2 = import10.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'fa-caret-down': p0,
        'fa-caret-right': p1
      }
      ;
    });
    this._expr_6 = import12.UNINITIALIZED;
    this._expr_7 = import12.UNINITIALIZED;
    this._expr_8 = import12.UNINITIALIZED;
    this._expr_9 = import12.UNINITIALIZED;
    this._expr_10 = import12.UNINITIALIZED;
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_21
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.NgClass) && (5 === requestNodeIndex))) { return this._NgClass_5_3; }
    if (((token === import17.NgClass) && (7 === requestNodeIndex))) { return this._NgClass_7_3; }
    if (((token === import17.NgClass) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgClass_3_3; }
    if (((token === import22.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import19.NgFor) && (16 === requestNodeIndex))) { return this._NgFor_16_6; }
    if (((token === import17.NgClass) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._NgClass_1_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import12.SimpleChange} = (null as any);
    const currVal_2:any = this._map_0(true,this.context.$implicit.items,(this._el_1 == this.parent.context.activeItem));
    if (import10.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_1_3.ngClass = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgClass_1_3.ngDoCheck(); }
    const currVal_3:any = 'ui-menuitem-link ui-corner-all ui-submenu-link';
    if (import10.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgClass_3_3.klass = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._map_1(((this._el_3 == this.parent.context.activeLink) && !this.context.$implicit.disabled),this.context.$implicit.disabled);
    if (import10.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgClass_3_3.ngClass = currVal_4;
      this._expr_4 = currVal_4;
    }
    if (!throwOnChange) { this._NgClass_3_3.ngDoCheck(); }
    const currVal_5:any = 'ui-submenu-icon fa fa-fw';
    if (import10.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgClass_5_3.klass = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._map_2((this.parent.context.orientation == 'horizontal'),(this.parent.context.orientation == 'vertical'));
    if (import10.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgClass_5_3.ngClass = currVal_6;
      this._expr_6 = currVal_6;
    }
    if (!throwOnChange) { this._NgClass_5_3.ngDoCheck(); }
    const currVal_7:any = 'ui-menuitem-icon fa fa-fw';
    if (import10.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgClass_7_3.klass = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.context.$implicit.icon;
    if (import10.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgClass_7_3.ngClass = currVal_8;
      this._expr_8 = currVal_8;
    }
    if (!throwOnChange) { this._NgClass_7_3.ngDoCheck(); }
    changes = (null as any);
    const currVal_10:any = this.context.$implicit.items;
    if (import10.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgFor_16_6.ngForOf = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import12.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgFor_16_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_16_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_9:any = import10.interpolate(1,'\n                            ',this.context.$implicit.label,'\n                        ');
    if (import10.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_8,currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_mouseenter_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onItemMouseEnter($event,this._el_1,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_1_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onItemMouseLeave($event,this._el_1)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_MegaMenu1(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement):import7.AppView<any> {
  return new _View_MegaMenu1(viewUtils,parentInjector,declarationEl);
}
class _View_MegaMenu2 extends import7.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import8.AppElement;
  _TemplateRef_3_5:any;
  _NgFor_3_6:import19.NgFor;
  _text_4:any;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement) {
    super(_View_MegaMenu2,renderType_MegaMenu,import11.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import12.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n                                        ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n                                            ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._appEl_3 = new import8.AppElement(3,1,this,this._anchor_3);
    this._TemplateRef_3_5 = new import22.TemplateRef_(this._appEl_3,viewFactory_MegaMenu3);
    this._NgFor_3_6 = new import19.NgFor(this._appEl_3.vcRef,this._TemplateRef_3_5,this.parent.parent.parentInjector.get(import20.IterableDiffers),this.parent.parent.ref);
    this._text_4 = this.renderer.createText(this._el_1,'\n                                        ',(null as any));
    this._text_5 = this.renderer.createText((null as any),'\n                                    ',(null as any));
    this._expr_0 = import12.UNINITIALIZED;
    this._expr_1 = import12.UNINITIALIZED;
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_5
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import19.NgFor) && (3 === requestNodeIndex))) { return this._NgFor_3_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import12.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this.context.$implicit;
    if (import10.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_3_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import12.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_3_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_3_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.parent.context.getColumnClass(this.parent.context.$implicit);
    if (import10.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_1,'className',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MegaMenu2(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement):import7.AppView<any> {
  return new _View_MegaMenu2(viewUtils,parentInjector,declarationEl);
}
class _View_MegaMenu3 extends import7.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import8.AppElement;
  _TemplateRef_7_5:any;
  _NgFor_7_6:import19.NgFor;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement) {
    super(_View_MegaMenu3,renderType_MegaMenu,import11.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import12.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n                                                ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'ul',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','ui-menu-list ui-helper-reset');
    this._text_2 = this.renderer.createText(this._el_1,'\n                                                    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'li',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','ui-widget-header ui-corner-all');
    this._el_4 = this.renderer.createElement(this._el_3,'h3',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_1,'\n                                                    ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._appEl_7 = new import8.AppElement(7,1,this,this._anchor_7);
    this._TemplateRef_7_5 = new import22.TemplateRef_(this._appEl_7,viewFactory_MegaMenu4);
    this._NgFor_7_6 = new import19.NgFor(this._appEl_7.vcRef,this._TemplateRef_7_5,this.parent.parent.parent.parentInjector.get(import20.IterableDiffers),this.parent.parent.parent.ref);
    this._text_8 = this.renderer.createText(this._el_1,'\n                                                ',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n                                            ',(null as any));
    this._expr_0 = import12.UNINITIALIZED;
    this._expr_1 = import12.UNINITIALIZED;
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_9
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._text_9
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import19.NgFor) && (7 === requestNodeIndex))) { return this._NgFor_7_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import12.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this.context.$implicit.items;
    if (import10.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_7_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import12.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_7_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_7_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import10.interpolate(1,'',this.context.$implicit.label,'');
    if (import10.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MegaMenu3(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement):import7.AppView<any> {
  return new _View_MegaMenu3(viewUtils,parentInjector,declarationEl);
}
class _View_MegaMenu4 extends import7.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _NgClass_2_3:import17.NgClass;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import8.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import23.NgIf;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _map_0:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement) {
    super(_View_MegaMenu4,renderType_MegaMenu,import11.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import12.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-menuitem ui-widget ui-corner-all');
    this._text_1 = this.renderer.createText(this._el_0,'\n                                                        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','ui-menuitem-link ui-corner-all');
    this._NgClass_2_3 = new import17.NgClass(this.parent.parent.parent.parent.parentInjector.get(import20.IterableDiffers),this.parent.parent.parent.parent.parentInjector.get(import21.KeyValueDiffers),new import13.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n                                                            ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_4 = new import8.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import22.TemplateRef_(this._appEl_4,viewFactory_MegaMenu5);
    this._NgIf_4_6 = new import23.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n                                                            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'span',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','ui-menuitem-text');
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n                                                        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n                                                    ',(null as any));
    this._expr_3 = import12.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'mouseenter',this.eventHandler(this._handle_mouseenter_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'mouseleave',this.eventHandler(this._handle_mouseleave_2_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_2.bind(this)));
    this._expr_4 = import12.UNINITIALIZED;
    this._map_0 = import10.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'ui-state-hover': p0,
        'ui-state-disabled': p1
      }
      ;
    });
    this._expr_5 = import12.UNINITIALIZED;
    this._expr_6 = import12.UNINITIALIZED;
    this._expr_7 = import12.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import23.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    if (((token === import17.NgClass) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._NgClass_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = 'ui-menuitem-link ui-corner-all';
    if (import10.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgClass_2_3.klass = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._map_0(((this._el_2 == this.parent.parent.parent.parent.context.hoveredItem) && !this.context.$implicit.disabled),this.context.$implicit.disabled);
    if (import10.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgClass_2_3.ngClass = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (!throwOnChange) { this._NgClass_2_3.ngDoCheck(); }
    const currVal_6:any = this.context.$implicit.icon;
    if (import10.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_4_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = (this.context.$implicit.url || '#');
    if (import10.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_2,'href',this.viewUtils.sanitizer.sanitize(import24.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    const currVal_7:any = import10.interpolate(1,'',this.context.$implicit.label,'');
    if (import10.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_mouseenter_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.parent.parent.parent.context.hoveredItem = $event.target)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.parent.parent.parent.context.hoveredItem = (null as any))) !== false);
    return (true && pd_0);
  }
  private _handle_click_2_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.parent.context.itemClick($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_MegaMenu4(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement):import7.AppView<any> {
  return new _View_MegaMenu4(viewUtils,parentInjector,declarationEl);
}
class _View_MegaMenu5 extends import7.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import17.NgClass;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement) {
    super(_View_MegaMenu5,renderType_MegaMenu,import11.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import12.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','ui-menuitem-icon fa fa-fw');
    this._NgClass_0_3 = new import17.NgClass(this.parent.parent.parent.parent.parent.parentInjector.get(import20.IterableDiffers),this.parent.parent.parent.parent.parent.parentInjector.get(import21.KeyValueDiffers),new import13.ElementRef(this._el_0),this.renderer);
    this._expr_0 = import12.UNINITIALIZED;
    this._expr_1 = import12.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.NgClass) && (0 === requestNodeIndex))) { return this._NgClass_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'ui-menuitem-icon fa fa-fw';
    if (import10.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgClass_0_3.klass = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.$implicit.icon;
    if (import10.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_0_3.ngClass = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgClass_0_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MegaMenu5(viewUtils:import10.ViewUtils,parentInjector:import4.Injector,declarationEl:import8.AppElement):import7.AppView<any> {
  return new _View_MegaMenu5(viewUtils,parentInjector,declarationEl);
}