/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../components/spinner/spinner';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '../../../components/inputtext/inputtext';
import * as import4 from '@angular/common/src/localization';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/i18n/tokens';
import * as import7 from '@angular/core/src/render/api';
import * as import8 from '@angular/core/src/linker/view';
import * as import9 from '@angular/core/src/linker/element';
import * as import10 from '../../../components/dom/domhandler';
import * as import11 from '@angular/core/src/linker/view_utils';
import * as import12 from '@angular/core/src/linker/view_type';
import * as import13 from '@angular/core/src/change_detection/change_detection';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/forms/src/directives/control_value_accessor';
import * as import16 from '@angular/core/src/metadata/view';
import * as import17 from '@angular/core/src/linker/component_factory';
import * as import18 from '@angular/common/src/directives/ng_class';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class SpinnerModuleInjector extends import0.NgModuleInjector<import1.SpinnerModule> {
  _CommonModule_0:import2.CommonModule;
  _InputTextModule_1:import3.InputTextModule;
  _SpinnerModule_2:import1.SpinnerModule;
  __LOCALE_ID_3:any;
  __NgLocalization_4:import4.NgLocaleLocalization;
  __TRANSLATIONS_FORMAT_5:any;
  constructor(parent:import5.Injector) {
    super(parent,[],[]);
  }
  get _LOCALE_ID_3():any {
    if ((this.__LOCALE_ID_3 == (null as any))) { (this.__LOCALE_ID_3 = (null as any)); }
    return this.__LOCALE_ID_3;
  }
  get _NgLocalization_4():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == (null as any))) { (this.__NgLocalization_4 = new import4.NgLocaleLocalization(this._LOCALE_ID_3)); }
    return this.__NgLocalization_4;
  }
  get _TRANSLATIONS_FORMAT_5():any {
    if ((this.__TRANSLATIONS_FORMAT_5 == (null as any))) { (this.__TRANSLATIONS_FORMAT_5 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_5;
  }
  createInternal():import1.SpinnerModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InputTextModule_1 = new import3.InputTextModule();
    this._SpinnerModule_2 = new import1.SpinnerModule();
    return this._SpinnerModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InputTextModule)) { return this._InputTextModule_1; }
    if ((token === import1.SpinnerModule)) { return this._SpinnerModule_2; }
    if ((token === import6.LOCALE_ID)) { return this._LOCALE_ID_3; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import6.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SpinnerModuleNgFactory:import0.NgModuleFactory<import1.SpinnerModule> = new import0.NgModuleFactory(SpinnerModuleInjector,import1.SpinnerModule);
var renderType_Spinner_Host:import7.RenderComponentType = (null as any);
class _View_Spinner_Host0 extends import8.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import9.AppElement;
  _DomHandler_0_4:import10.DomHandler;
  _Spinner_0_5:import1.Spinner;
  __NG_VALUE_ACCESSOR_0_6:any[];
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import11.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Spinner_Host0,renderType_Spinner_Host,import12.ViewType.HOST,viewUtils,parentInjector,declarationEl,import13.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_0_6():any[] {
    if ((this.__NG_VALUE_ACCESSOR_0_6 == (null as any))) { (this.__NG_VALUE_ACCESSOR_0_6 = [this._Spinner_0_5]); }
    return this.__NG_VALUE_ACCESSOR_0_6;
  }
  createInternal(rootSelector:string):import9.AppElement {
    this._el_0 = this.selectOrCreateHostElement('p-spinner',rootSelector,(null as any));
    this._appEl_0 = new import9.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Spinner0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DomHandler_0_4 = new import10.DomHandler();
    this._Spinner_0_5 = new import1.Spinner(new import14.ElementRef(this._el_0),this._DomHandler_0_4);
    this._appEl_0.initComponent(this._Spinner_0_5,[],compView_0);
    compView_0.create(this._Spinner_0_5,this.projectableNodes,(null as any));
    this._expr_0 = import13.UNINITIALIZED;
    this._expr_1 = import13.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.DomHandler) && (0 === requestNodeIndex))) { return this._DomHandler_0_4; }
    if (((token === import1.Spinner) && (0 === requestNodeIndex))) { return this._Spinner_0_5; }
    if (((token === import15.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Spinner_0_5.filled;
    if (import11.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'ui-inputwrapper-filled',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Spinner_0_5.focus;
    if (import11.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'ui-inputwrapper-focus',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Spinner_0_5.ngAfterViewInit(); } }
  }
}
function viewFactory_Spinner_Host0(viewUtils:import11.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<any> {
  if ((renderType_Spinner_Host === (null as any))) { (renderType_Spinner_Host = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,[],{})); }
  return new _View_Spinner_Host0(viewUtils,parentInjector,declarationEl);
}
export const SpinnerNgFactory:import17.ComponentFactory<import1.Spinner> = new import17.ComponentFactory<import1.Spinner>('p-spinner',viewFactory_Spinner_Host0,import1.Spinner);
const styles_Spinner:any[] = [];
var renderType_Spinner:import7.RenderComponentType = (null as any);
class _View_Spinner0 extends import8.AppView<import1.Spinner> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _InputText_3_3:import3.InputText;
  _text_4:any;
  _el_5:any;
  _NgClass_5_3:import18.NgClass;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _NgClass_13_3:import18.NgClass;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_25:any;
  _map_0:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_31:any;
  _map_1:any;
  /*private*/ _expr_32:any;
  constructor(viewUtils:import11.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement) {
    super(_View_Spinner0,renderType_Spinner,import12.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import13.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'span',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','ui-spinner ui-widget ui-corner-all');
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'input',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','ui-spinner-input');
    this.renderer.setElementAttribute(this._el_3,'pInputText','');
    this.renderer.setElementAttribute(this._el_3,'type','text');
    this._InputText_3_3 = new import3.InputText(new import14.ElementRef(this._el_3));
    this._text_4 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_1,'a',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','ui-spinner-button ui-spinner-up ui-corner-tr ui-button ui-widget ui-state-default ui-button-text-only');
    this._NgClass_5_3 = new import18.NgClass(this.parentInjector.get(import19.IterableDiffers),this.parentInjector.get(import20.KeyValueDiffers),new import14.ElementRef(this._el_5),this.renderer);
    this._text_6 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'span',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','ui-button-text');
    this._text_8 = this.renderer.createText(this._el_7,'\n                    ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','fa fa-fw fa-caret-up');
    this._text_10 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._text_12 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_1,'a',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','ui-spinner-button ui-spinner-down ui-corner-br ui-button ui-widget ui-state-default ui-button-text-only');
    this._NgClass_13_3 = new import18.NgClass(this.parentInjector.get(import19.IterableDiffers),this.parentInjector.get(import20.KeyValueDiffers),new import14.ElementRef(this._el_13),this.renderer);
    this._text_14 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'span',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','ui-button-text');
    this._text_16 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'span',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','fa fa-fw fa-caret-down');
    this._text_18 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_21 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._expr_9 = import13.UNINITIALIZED;
    this._expr_10 = import13.UNINITIALIZED;
    this._expr_11 = import13.UNINITIALIZED;
    this._expr_12 = import13.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_3,'keydown',this.eventHandler(this._handle_keydown_3_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_3,'input',this.eventHandler(this._handle_input_3_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_3,'blur',this.eventHandler(this._handle_blur_3_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_3,'change',this.eventHandler(this._handle_change_3_3.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_3,'focus',this.eventHandler(this._handle_focus_3_4.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_3,'mouseover',this.eventHandler(this._handle_mouseover_3_5.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_3,'mouseout',this.eventHandler(this._handle_mouseout_3_6.bind(this)));
    this._expr_13 = import13.UNINITIALIZED;
    this._expr_14 = import13.UNINITIALIZED;
    this._expr_15 = import13.UNINITIALIZED;
    this._expr_16 = import13.UNINITIALIZED;
    this._expr_17 = import13.UNINITIALIZED;
    this._expr_18 = import13.UNINITIALIZED;
    this._expr_19 = import13.UNINITIALIZED;
    this._expr_20 = import13.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_5,'mouseenter',this.eventHandler(this._handle_mouseenter_5_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_5,'mouseleave',this.eventHandler(this._handle_mouseleave_5_1.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_5,'mousedown',this.eventHandler(this._handle_mousedown_5_2.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_5,'mouseup',this.eventHandler(this._handle_mouseup_5_3.bind(this)));
    this._expr_25 = import13.UNINITIALIZED;
    this._map_0 = import11.pureProxy3((p0:any,p1:any,p2:any):{[key: string]:any} => {
      return {
        'ui-state-hover': p0,
        'ui-state-active': p1,
        'ui-state-disabled': p2
      }
      ;
    });
    this._expr_26 = import13.UNINITIALIZED;
    var disposable_11:Function = this.renderer.listen(this._el_13,'mouseenter',this.eventHandler(this._handle_mouseenter_13_0.bind(this)));
    var disposable_12:Function = this.renderer.listen(this._el_13,'mouseleave',this.eventHandler(this._handle_mouseleave_13_1.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_13,'mousedown',this.eventHandler(this._handle_mousedown_13_2.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_13,'mouseup',this.eventHandler(this._handle_mouseup_13_3.bind(this)));
    this._expr_31 = import13.UNINITIALIZED;
    this._map_1 = import11.pureProxy3((p0:any,p1:any,p2:any):{[key: string]:any} => {
      return {
        'ui-state-hover': p0,
        'ui-state-active': p1,
        'ui-state-disabled': p2
      }
      ;
    });
    this._expr_32 = import13.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.InputText) && (3 === requestNodeIndex))) { return this._InputText_3_3; }
    if (((token === import18.NgClass) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._NgClass_5_3; }
    if (((token === import18.NgClass) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgClass_13_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_25:any = 'ui-spinner-button ui-spinner-up ui-corner-tr ui-button ui-widget ui-state-default ui-button-text-only';
    if (import11.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._NgClass_5_3.klass = currVal_25;
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._map_0(this.context.hoverUp,this.context.activeUp,this.context.disabled);
    if (import11.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._NgClass_5_3.ngClass = currVal_26;
      this._expr_26 = currVal_26;
    }
    if (!throwOnChange) { this._NgClass_5_3.ngDoCheck(); }
    const currVal_31:any = 'ui-spinner-button ui-spinner-down ui-corner-br ui-button ui-widget ui-state-default ui-button-text-only';
    if (import11.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._NgClass_13_3.klass = currVal_31;
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._map_1(this.context.hoverDown,this.context.activeDown,this.context.disabled);
    if (import11.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this._NgClass_13_3.ngClass = currVal_32;
      this._expr_32 = currVal_32;
    }
    if (!throwOnChange) { this._NgClass_13_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_9:any = this.context.size;
    if (import11.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementAttribute(this._el_3,'size',((currVal_9 == (null as any))? (null as any): currVal_9.toString()));
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this.context.maxlength;
    if (import11.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_3,'maxLength',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this.context.disabled;
    if (import11.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_3,'disabled',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this.context.readonly;
    if (import11.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementProperty(this._el_3,'readOnly',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = true;
    if (import11.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_3,'ui-inputtext',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = true;
    if (import11.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_3,'ui-corner-all',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = true;
    if (import11.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_3,'ui-state-default',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = true;
    if (import11.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_3,'ui-widget',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._InputText_3_3.hover;
    if (import11.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_3,'ui-state-hover',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._InputText_3_3.focus;
    if (import11.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_3,'ui-state-focus',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._InputText_3_3.disabled;
    if (import11.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_3,'ui-state-disabled',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._InputText_3_3.filled;
    if (import11.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_3,'ui-state-filled',currVal_20);
      this._expr_20 = currVal_20;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_keydown_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onInputKeydown($event,this._el_3)) !== false);
    return (true && pd_0);
  }
  private _handle_input_3_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onInput($event,this._el_3)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_3_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onBlur(this._el_3)) !== false);
    const pd_1:any = ((<any>this._InputText_3_3.onBlur($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_change_3_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.handleChange($event)) !== false);
    return (true && pd_0);
  }
  private _handle_focus_3_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onFocus()) !== false);
    const pd_1:any = ((<any>this._InputText_3_3.onFocus($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_mouseover_3_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._InputText_3_3.onMouseover($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseout_3_6($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._InputText_3_3.onMouseout($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onUpButtonMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_5_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onUpButtonMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_5_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onUpButtonMousedown($event,this._el_3)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_5_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onUpButtonMouseup($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseenter_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onDownButtonMouseenter($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_13_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onDownButtonMouseleave($event)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_13_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onDownButtonMousedown($event,this._el_3)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseup_13_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onDownButtonMouseup($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Spinner0(viewUtils:import11.ViewUtils,parentInjector:import5.Injector,declarationEl:import9.AppElement):import8.AppView<import1.Spinner> {
  if ((renderType_Spinner === (null as any))) { (renderType_Spinner = viewUtils.createRenderComponentType('c:/Users/eirwn/Documents/primeng-min/components/spinner/spinner.ts class Spinner - inline template',0,import16.ViewEncapsulation.None,styles_Spinner,{})); }
  return new _View_Spinner0(viewUtils,parentInjector,declarationEl);
}